### ISSUE TITLE
Difference in genome numbers: portal vs NCBI

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#100]
I just wanted to document this unless we want to review this.

**Comment by hdliv** [comment]
@abusalehmdtayeen and I have already talked on why there is a difference...

**Comment by arlin** [comment]
so, can you document that here, so that we have a record of it?

**Comment by hdliv** [comment]
the problem with genome numbers between the portal vs NCBi derives from NCBI counting different varieties or forms and/or strains of the same binomial as unique genomes.  The portal uses only binomials (not considering lower level taxonomy), so the count is less
