### ISSUE TITLE
capability to export extracted name list from portal

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#101]
It would be nice to be able to export both the species list and taxon matching report from the portal.

**Comment by ducvan0212** [comment]
@hdliv Do you mean about generating downloadable documents of species list and taxon matching report?

**Comment by ducvan0212** [comment]
Do you suggest that we should allow users to download species list as well as taxon matching report?

**Comment by hdliv** [comment]
Yes.

**Comment by ducvan0212** [comment]
@hdliv Would you please specify what should be exported from species list? Provide an example to illustrate your idea.

I already implemented exporting taxon matching report to pdf :)
