### ISSUE TITLE
taxon services

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#104]
![screen shot 2016-06-20 at 4 44 28 pm](https://cloud.githubusercontent.com/assets/1614884/16212668/96f0cbf0-3706-11e6-90e7-ea33503cbd61.png)

In Taxon finder, user can choose a combination of options. Which services will be used to get names when user chooses both NCBI and location?

**Comment by ducvan0212** [comment]
@abusalehmdtayeen Where can I reach the location service?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : You can find it in web service 7 of this document https://github.com/phylotastic/phylo_services_docs/blob/master/ServiceDescription/PhyloServicesDescription.md

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I think user will not choose combination of options. Just any of the options. But check with Arlin and Dail. I may be  wrong. You can mention this issue in the upcoming meeting this week.

**Comment by ducvan0212** [comment]
Thank you @abusalehmdtayeen 
Can @arlin and @hdliv make things clear for me?
