### ISSUE TITLE
error when calling taxon service

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#105]
http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/country_species?taxon=Panthera%20onca&country=United%20States

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Fixed.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen  

Connection refused - connect(2) for "phylo.cs.nmsu.edu" port 5004
Error: GET http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/country_species?taxon=Equus&country=United States

List species service is also down. I think someone restarted  the server without notifying us again.
