### ISSUE TITLE
sign-in error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#108]
I can't sign in.
![screen shot 2016-07-01 at 1 47 09 pm](https://cloud.githubusercontent.com/assets/1659198/16529712/6e2517e6-3f92-11e6-8723-1a9e47dde48b.png)

**Comment by arlin** [comment]
temporary solution is to replace URL with "phylo.cs.nmsu.edu" instead of the IP.  Then when I try to log in, it works.  Are users going to have this problem?  Maybe this is not a real bug.  It only happens if I start by navigating to  128.123.63.10

**Comment by ducvan0212** [comment]
Google app does not allow IP address in callback request so you have to use domain name to sign in, @arlin . I remember this problem was discussed with @thanhnh-infinity.
