### ISSUE TITLE
DCA template

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#109]
on the portal when choosing to upload DCA there is a template.  
However the list.csv and species.csv do not open to give the user the example.

**Comment by ducvan0212** [comment]
Can you provide me a DCA template?

**Comment by hdliv** [comment]
@ducvan0212 I will send this via email

**Comment by ducvan0212** [comment]
I expected user download and edit template file. Google drive dont allow user to have preview of csv file.

**Comment by hdliv** [comment]
is there another way to do this?

**Comment by ducvan0212** [comment]
I will let users download it

**Comment by hdliv** [comment]
ok

**Comment by hdliv** [comment]
great!

**Comment by ducvan0212** [comment]
I changed link. Now user has to download the template

**Comment by hdliv** [comment]
@ducvan0212 i saw this so moving to done
