### ISSUE TITLE
Subset 'Location' not functioning

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#112]
in 'choose taxon' the ability to restrain a subset by location  --- you can tick the box but there are no countries that appear in the scroll down

**Comment by ducvan0212** [comment]
I added a few countries for test purpose.

**Comment by ducvan0212** [comment]
A complete list of countries now is available in portal ;)

**Comment by arlin** [comment]
@ducvan0212 if you want us to review this, move it into review.
