### ISSUE TITLE
name dropped from uploaded list

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#113]
I uploaded the list of 5 species below, but the portal only shows me 4.  Even if a name is not found in OpenTree's taxonomy, we should present the name in its own row.  This is the feature that users want-- the taxon report should show the result for every input name, even if the there is no match

Bos taurus
Ovis aries
Hippopotamus amphibius
Balaenoptera acutorostrata
Megaptera novaeangliae

**Comment by ducvan0212** [comment]
@arlin I checked. Hippo didnot represent in response from finding names service. The service did fail to detect Hippopotamus amphibius. Can @abusalehmdtayeen verify this issue?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I tried the tnrs service (http://phylo.cs.nmsu.edu:5004/phylotastic_ws/tnrs/ot/resolve?names=Bos%20taurus|Ovis%20aries|Hippopotamus%20amphibius|Balaenoptera%20acutorostrata|Megaptera%20novaeangliae) with all 5 species and it returned me match for all of them. It seems that the problem is not within the web service. Would you  please check your end carefully?

**Comment by ducvan0212** [comment]
You should use extracting names from files service because Arlin put 5 these names into a file. I remember I called service 2 to extract names.

**Comment by ducvan0212** [comment]
It is fine, I will refactor my endpoint.

**Comment by ducvan0212** [comment]
I finished upgrade portal. Now, you can upload a one-name-per-line list and if there is any names that can not be resolved, portal will display these names and allow you to edit them.

**Comment by arlin** [comment]
OK.  The first issue (no hippo from OT) seems to have disappeared.   The second issue was not providing a line item for un-matched names.  This has now been fixed. which I can verify with the list below, which includes 5 real and 5 imaginary species (unicorn, selki, kraken, chimaera, dragon). 

![image](https://cloud.githubusercontent.com/assets/1659198/17192885/79a7c87a-541e-11e6-90ae-206e59319073.png)
