### ISSUE TITLE
improve interface to edit list item

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#115]
The current interface is a bit confusing.  Unmatched list items are presented in a rectangular box, and there is a "change" button to the right (see image).  My first instinct as a user was to click "change" and then edit the box, but this has no effect.  Instead, what works is to edit the text in the box first, then click "change".  Here is what I suggest to make this clearer: 

1. "Unresolved species" --> "Unmatched names"
2. "Change" (button label) --> "Search" 
3.  "Scientific names (*)" --> "Edit name as desired, then click the 'Search' button to look for matches"

![screen shot 2016-08-04 at 12 34 55 pm](https://cloud.githubusercontent.com/assets/1659198/17410182/9b14ab68-5a40-11e6-8d35-2938c14ab4d4.png)

**Comment by ducvan0212** [comment]
Thank you @arlin, I made changes as your suggestions.

**Comment by arlin** [comment]
Thanks @ducvan0212 !  I'm sorry for the delay in getting to this.  The changes are good.  

However, I discovered one bug that is very strange.  When I click on "Search" for the *first* item in the list, the portal responds by *attempting to get a tree*.  When I click on "Search" for any *other* item in the list, the portal resolves the name and adds it to the list.

**Comment by ducvan0212** [comment]
My typo made this mistake in HTML. I checked again and corrected my typo so it should be no problem now, @arlin.

**Comment by arlin** [comment]
OK, good.  It works now.  :-)
