### ISSUE TITLE
second odd result from list

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#117]
Use the list "phytozome_cleaned.txt" (https://github.com/phylotastic/phylotastic/blob/master/testing/Examples/phytozome_cleaned.txt)

Get the tree. There are 2 anomalies. This is the second one: one of the OTU names is `&#39`.  

I believe that this problem is on our end.  I think the back-end name might have a double-single-quoted name inside a single-quoted string `'Ostreococcus ''lucimarinus''_ott851102'`

![screen shot 2016-08-04 at 1 05 59 pm](https://cloud.githubusercontent.com/assets/1659198/17411025/625e75de-5a44-11e6-82c0-7576b48ccc4e.png)
".

**Comment by ducvan0212** [comment]
My computer is having problem. I will check my end for this issue. I also saw you added FAQ and About pages but I can not deploy to the server for now. I will check them as soon as I can.

**Comment by ducvan0212** [comment]
Unluckily, after the recovery, I guess my hard disk is broken. I will borrow my friend's machine and work with it a couple of days. It is also an oppotinity to test installation of the portal in a new enviroment.

**Comment by ducvan0212** [comment]
@arlin I fixed name display in tree. As you recognized, the single quote causes problem. Thank you!

**Comment by hdliv** [comment]
we are now usign ETE, so closing
