### ISSUE TITLE
Rename Lists

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#120]
Can we add the ability to rename lists on the portal?

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I checked in https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md but there is no update list service.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen It is also required to change list from private to public

**Comment by ducvan0212** [comment]
@abusalehmdtayeen

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I will let you know when I finish. Is there any other feature you want other than renaming and changing list type?

**Comment by ducvan0212** [comment]
It depends on your design. I think it is better to change everything so if next few weeks, there is request to change date, you wont need to re-implement anything. But please keep the request for update list simple. Thank you in advance

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I have added an API to update list meta-data. It is very simple. You can update value of any list property (not list content) you want. Check the documentation https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I cannot update both title and public attribute in one request

**Comment by ducvan0212** [comment]
Hmm, it works now, @abusalehmdtayeen.

**Comment by hdliv** [comment]
I have tested this and it works
