### ISSUE TITLE
Name Trees

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#121]
After 'Get Tree' the tree is generated with a number.  We should be able to name and rename these trees.

**Comment by ducvan0212** [comment]
Now, when you push "Get tree", a pop up is displayed so you can fill in name of tree. If you want to edit tree name, you can look for "Edit tree name" button in Tree actions section of Tree viewer tab

**Comment by hdliv** [comment]
@ducvan0212 I get this pop-up and am closing the issue
