### ISSUE TITLE
metadata for tree

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#122]
Content of metadata tab in home page

**Comment by ducvan0212** [comment]
Can you provide me a sample of metadata of a list?

**Comment by hdliv** [comment]
@ducvan0212 is this the same as issue #109

**Comment by ducvan0212** [comment]
I received your email. How can I query information like this?

**Comment by ducvan0212** [comment]
@hdliv

**Comment by hdliv** [comment]
@ducvan0212 and @hdliv have created the metadata table, and received initial input from @arlin

**Comment by ducvan0212** [comment]
Can I start implementing? Are you still keen on placing 'comments' inside metadata tab?

**Comment by ducvan0212** [comment]
@hdliv

**Comment by hdliv** [comment]
@ducvan0212 OK for implementing

**Comment by hdliv** [comment]
@ducvan0212 is this finished for now?

**Comment by arlin** [comment]
@ducvan0212 see phylotastic/phylotastic#145 for links to the draft metadata model.  @hdliv can work with you on implementing this in the portal.

**Comment by arlin** [comment]
thanks @ducvan.   we now have a good start on the metadata model.  we need to get some feedback from users now.
