### ISSUE TITLE
Ability to delete lists

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#123]
We should have a way to delete our private lists and those we have made public

**Comment by ducvan0212** [comment]
@hdliv I just added a button to delete a list and put it temporarily in Metadata tab. When I know how to query metadata query for an arbitrary list, I will make the interface better.

**Comment by hdliv** [comment]
@ducvan0212 can you put the delete button on the side as you have done for the tree viewer?

**Comment by ducvan0212** [comment]
I put delete and edit list button on the side

**Comment by hdliv** [comment]
Great.
