### ISSUE TITLE
Newick download

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#125]
Remove ottids and underscores in the newick file that can be downloaded from the tree viewer page.

**Comment by ducvan0212** [comment]
I removed ottids and underscores in the popup when you click "show newick" button in tree viewer page. I am not sure which file you can download. Can you give me more details?

**Comment by hdliv** [comment]
@ducvan0212 You are right.  I dont download it.  I copy and paste the newick file into a text editor.  Maybe we can bypass this step as allowing to download right away

**Comment by hdliv** [comment]
anyways. the newick file without the ottids and underscores looks great.

**Comment by ducvan0212** [comment]
I think this issue is resolved @hdliv

**Comment by hdliv** [comment]
@ducvan0212 yes  movin it to in review

**Comment by ducvan0212** [comment]
What do you mean? Do you want each species in a line?

**Comment by hdliv** [comment]
@ducvan0212 moving to done -- i see that you have implemented
