### ISSUE TITLE
Export List

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#126]
We need a feature to export the list as a .txt.  It should be of all the 'selected' species.

**Comment by ducvan0212** [comment]
What is format of the text file? Can you give me an example?

**Comment by hdliv** [comment]
@ducvan0212 i sent you an example

**Comment by ducvan0212** [comment]
So basically, the exported file is one-name-per-line

**Comment by hdliv** [comment]
yes.  Like the list that we import.

**Comment by ducvan0212** [comment]
@hdliv Added this feature

**Comment by hdliv** [comment]
@ducvan0212 great  I have tried it out
