### ISSUE TITLE
Drag and drop list

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#127]
It would be nice to have a feature where we are able to drag and drop our input file instead of always searching for the file.

This feature actually is implemented, but looking at the current layout, I would not know that we could do that

**Comment by ducvan0212** [comment]
I created a box so you can drop your file on. Please take a look

**Comment by hdliv** [comment]
can we talk about  this?  The box is not in all

**Comment by ducvan0212** [comment]
Can you check again? @hdliv

**Comment by hdliv** [comment]
@ducvan0212 great!!  moving issue to done
