### ISSUE TITLE
Remove duplicate taxon names

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#128]
When extracting from doc, the species list returned can contain the same taxon listed several times.  

Each taxon should only be listed once.

**Comment by hdliv** [comment]
![screen shot 2016-08-18 at 14 12 16](https://cloud.githubusercontent.com/assets/6361361/17785371/7134eb78-654e-11e6-9c67-78699654084d.png)

**Comment by hdliv** [comment]
![screen shot 2016-08-18 at 14 12 08](https://cloud.githubusercontent.com/assets/6361361/17785379/750c2e3c-654e-11e6-9c13-909107cbac73.png)

**Comment by ducvan0212** [comment]
This issue is duplicate with #84 @hdliv

**Comment by hdliv** [comment]
@ducvan0212 OK.  I will close this since we already have another issue for this
