### ISSUE TITLE
.pdf and .doc scraping

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#138]
I am not getting a list of species for .pdf or .doc I used as input list

**Comment by hdliv** [comment]
attaching the files
[biodiversity_data_journal-3-e4421.pdf](https://github.com/phylotastic/phylotastic-portal/files/445221/biodiversity_data_journal-3-e4421.pdf)

[Gama-Jr et al. 2014 - How diverse are coccoid Cyanobacteria'.pdf](https://github.com/phylotastic/phylotastic-portal/files/445224/Gama-Jr.et.al.2014.-.How.diverse.are.coccoid.Cyanobacteria.pdf)

**Comment by abusalehmdtayeen** [comment]
@hdliv : Today the GNRD service is down for some reason. Try later.

**Comment by hdliv** [comment]
OK.  It must have been down yesterday too when I tried

**Comment by abusalehmdtayeen** [comment]
@hdliv , Try the two pdf files again. GRND service is up now. You should be able to get a list of species for each file.

**Comment by hdliv** [comment]
@abusalehmdtayeen Yes I go the lists using TaxonFinder, but not with NetiNeti

**Comment by abusalehmdtayeen** [comment]
@hdliv , It is a GNRD issue. You have to ask Dima about it.

**Comment by hdliv** [comment]
@dimus I haven't tried today, but I am able to scrape with TaxonFinder and not NetiNeti.  Is there a reason why?

**Comment by dimus** [comment]
do you have a url for pdf that did not work? @hdliv? I am able to find names with NetiNeti

**Comment by dimus** [comment]
lookd like language detection problem, our bayes classifier did not recognize the text as English. Try to switch of language detection in options

**Comment by arlin** [comment]
what is the status of this ticket?   It seems to me that if we need to control language detection options, then we want to add that to the (1) phylotastic web service wrapper for GNRD and (2) possibly support that choice in the portal UI.

**Comment by dimus** [comment]
There is a switch for language detection in API, however I would leave it on as default, as it does save from many false positives in non-english texts

**Comment by abusalehmdtayeen** [comment]
In GNRD detect_language parameter is turned on by default. The same is true for phylotastic wrapper web service.

**Comment by hdliv** [comment]
@abusalehmdtayeen I will move this over to In review.  Great
