### ISSUE TITLE
Not all lists give trees

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#139]
I am having trouble with getting a tree for some lists

**Comment by hdliv** [comment]
I attach the example of one  
[aquaticxterrestrial.txt](https://github.com/phylotastic/phylotastic-portal/files/445231/aquaticxterrestrial.txt)

**Comment by ducvan0212** [comment]
The tree itself is contructed but the problem is it can not visualized. Refer to #134

**Comment by hdliv** [comment]
@ducvan0212 I am closing the issue since this issue is in another ticket.
