### ISSUE TITLE
delete list when process fails

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#140]
There are cases when uploads fail or are in wrong format but I can't seem to delete the task, only re-upload

**Comment by hdliv** [comment]
![screen shot 2016-08-30 at 11 09 27](https://cloud.githubusercontent.com/assets/6361361/18094722/6a271722-6ea2-11e6-8160-e960617ea09a.png)

**Comment by ducvan0212** [comment]
You can re-upload instead of deleting and uploading another file.

**Comment by hdliv** [comment]
yes, but then i have this red box that i want to take away

**Comment by arlin** [comment]
What is the status of this?   @hdliv, if there is still an issue, can you please provide an example for re-creating it?

**Comment by ducvan0212** [comment]
@arlin I forgot to ping @hdliv to check the delete button after I implemented it. Sorry about that.

**Comment by hdliv** [comment]
@arlin @ducvan0212 i now see the delete button and it works.  i will close this issue
