### ISSUE TITLE
Problem when scraping URL

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#141]
When scraping the Ant Wiki page (https://en.wikipedia.org/wiki/Ant) the List rendered contained **320** matches.  Removing the dupes, the list has only **270** matches.  

The tree rendered after **Get Tree**  has only **177** tips.

I suppose this is because there are internal nodes and tips scraped together.  However, this can confuse a user.

Also, in this case, the .nwk downloaded is not read due to dupes and formatting problems in the .nwk file.

**Comment by hdliv** [comment]
The files

[Species_found_ant_wiki.txt](https://github.com/phylotastic/phylotastic-portal/files/445276/Species_found_ant_wiki.txt)

[Species_found_ant_wiki_no dupes.txt](https://github.com/phylotastic/phylotastic-portal/files/445278/Species_found_ant_wiki_no.dupes.txt)

[Wiki_ants_tree.txt](https://github.com/phylotastic/phylotastic-portal/files/445283/Wiki_ants_tree.txt)
![screen shot 2016-08-30 at 11 09 27](https://cloud.githubusercontent.com/assets/6361361/18095456/0c7cbd9a-6ea5-11e6-835c-5f58223b1a31.png)

**Comment by ducvan0212** [comment]
Please tell me what I can do to resolve this issue

**Comment by hdliv** [comment]
@ducvan0212 I dont think we came to a conclusion during last week's meeting

**Comment by hdliv** [comment]
@ducvan0212 we dont have a method to resolve this right now.  I will close the issue and if this is important down the road -- a new issue can be created

**Comment by arlin** [comment]
@hdliv, IMHO this means that the issue goes back on the back-log.  The only things that go into "closed" are fixed, duplicates, and wontfix.

**Comment by hdliv** [comment]
I dont know IMHO.  However, I closed it as a wontfix.
