### ISSUE TITLE
Authorization asks for far reaching and potentially excessive privileges

### ISSUE THREAD

**Issue by hlapp** [phylotastic/phylotastic-portal#145]
The Google Auth screen states that the application not only wants view access to my email address and basic profile info (which I’d be OK with letting it view), but also wants to _Manage your data while you are not signed in_.

Perhaps the app truly needs to have this access, but not having been told that it does and exactly why this is so, I aborted at that point - allowing an app in alpha stage to accidentally mess up or delete all the data in my Google account (while I'm logged in or not, actually) seemed a lot more risk than I am willing to take as a user who wants to give it a try.

**Comment by ducvan0212** [comment]
@thanhnh-infinity Can you check our google app?
@hlapp Thank you for your comments.

**Comment by thanhnh-infinity** [comment]
@ducvan0212 : It depends on the "scopes" parameter that you set up for OAuth2. Can you check it ?

**Comment by ducvan0212** [comment]
I requested email, profile and offline for scope. I removed offline scope now but my Google Auth screen has nothing change. Can @hdliv do me a favor that check this issue?

**Comment by hlapp** [comment]
It is changed for me now, it doesn't ask anymore for permission to manage my data.

**Comment by hdliv** [comment]
@ducvan0212   should i close this?

**Comment by ducvan0212** [comment]
@hdliv yes, please. Thank you.

**Comment by hdliv** [comment]
closing
