### ISSUE TITLE
sort list alphabetically

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#148]
In list view, present the list sorted alphabetically.  This makes it easier for the user to find a species.

**Comment by hdliv** [comment]
@arlin why is this in review?

**Comment by arlin** [comment]
I'm not seeing this consistently.  I uploaded a list via text file, and the species were presented alphabetically by the portal.  However, I scraped names from a PDF, and these do not appear alphabetically, e.g., look at 1:40 in https://youtu.be/5oKYu8GCMjc.

**Comment by ducvan0212** [comment]
I fixed this. I forgot to sort list species extracted from documents. :-)

**Comment by arlin** [comment]
OK, I have tested with URL, PDF and txt.  Good, thanks!

**Comment by arlin** [comment]
Now, we also need to sort the list of lists and the list of trees, to make these easier for the user to navigate.  But that is a separate ticket.
