### ISSUE TITLE
add styles for tree viewer

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#15]

**Comment by arlin** [comment]
This ticket is in progress but is not assigned to anyone.  Is @ducvan0212 working on this?

**Comment by hdliv** [comment]
is the treeviewer going to be interactive, where the user can move around branches  and root on different tips.

**Comment by arlin** [comment]
could you push to the server, please?  I'm not seeing anything different with the tree viewer.
