### ISSUE TITLE
fix newick string output

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#151]
Currently the newick window and export-as-text use different tree-strings.  The default should be *without* ottids.

1.  make sure that both methods output the same string. 
2. if desired, add an option to include OTT ids in the Newick string.

**Comment by ducvan0212** [comment]
I added option to download newick format with or without OTT ids and compared text output.

**Comment by arlin** [comment]
Thanks, @ducvan0212, this works fine :-)
