### ISSUE TITLE
toggle line highlight

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#152]
Currently there is no way to remove the "line highlight" feature from a clade in the tree view.   

By contrast, the box highlight feature toggles on and off.  

Fix the line highlight so that it can be turned off.

**Comment by abusalehmdtayeen** [comment]
@hdliv @arlin , Line Highlight now supports toggle on and off.

**Comment by hdliv** [comment]
@abusalehmdtayeen great i'll take a look

**Comment by arlin** [comment]
This is done.  Thanks.
