### ISSUE TITLE
feedback address

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#153]
Either add text and a link (1, 2), or simply embed the form (3). 

1. Text: We appreciate feedback on any aspect of the Phylotastic system.  Please use our online form at bit.ly/phylofeedback to report bugs, make feature requests, or relay comments.

2. Link to online form: http://bit.ly/phylofeedback

3.  Embed code (I removed the opening "<" and closing ">" so that waffle doesn't try to load this): 
  iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfQYgE9TAhVF5Mw8BiojUryCoWMbybrv4G1Jj_MgiCO5jn5cg/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe

**Comment by ducvan0212** [comment]
Thank you @arlin. I added feedback page and embedded code into the portal

**Comment by hdliv** [comment]
tested  the form through the portal -- ok
