### ISSUE TITLE
make NetiNeti + TaxonFinder default

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#154]
default search mode when using GNRD should combine NetiNeti and TaxonFinder.  This option is available via our web service already.  

The option to use  one or the other may be offered to the user, but this is not essential.

**Comment by ducvan0212** [comment]
I made this change. I added "NetiNeti & TaxonFinder" option in uploading document view.

**Comment by hdliv** [comment]
@ducvan0212 thanks.  I have tested and am now closing the issue
