### ISSUE TITLE
stable production server

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#155]
Set up a stable production server that is not the same as the site that we use internally to test and review new features.

**Comment by ducvan0212** [comment]
@arlin @epontell Can I have a server to install software needed for the portal? The current server is for web services and test environment.

**Comment by arlin** [comment]
@epontell @ducvan0212 let's talk about this today.   Van has been very busy.  The only thing standing between us and our soft release is this ticket.

**Comment by arlin** [comment]
at the f2f meeting, we decided that this is a priority and that the due date was in about a week.  this is the only thing stopping us from the soft release which is scheduled for next week.
