### ISSUE TITLE
remove fake branch lengths from tree views

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#158]
Currently the tree view shows branch lengths in red font, but they are all "1.0" because the branch lengths aren't real.   Remove the red numbers.  This can be added as an option. We may wish to show branch lengths later, when we start using DateLife.

**Comment by abusalehmdtayeen** [comment]
This feature is done. Now user has the option to turn on/off the show branch length feature.

**Comment by arlin** [comment]
We need to change this.  In other tree viewers, 99 % of the time, numeric branch lengths are rendered graphically *only by scaling the horizontal length of the branch image to the numeric branch length*.   It is very unusual to display the actual numbers.   Expert users will think that "show branch lengths" means to rescale the branch images.  

Please hide this option.   We can bring it back later if needed but for now it is just confusing.

**Comment by ducvan0212** [comment]
The option is hidden in the portal
