### ISSUE TITLE
sort lists of lists and trees

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#159]
This is not a high priority.  However, if the user has > 5 lists or trees, then it is helpful to sort them by name so that they are easier to find.  

Alternatively, we could use a "stack" and put the *newest* list or tree at the top.

**Comment by arlin** [comment]
Thanks.  This is an improvement but we need to remove case-sensitivity from sorting.  Currently, the lists are sorted 0 to 9 > A to Z > a to z.  

![screen shot 2016-09-28 at 9 18 03 am](https://cloud.githubusercontent.com/assets/1659198/18914850/bca198b2-855c-11e6-8e5c-f4e0da9e480e.png)

**Comment by ducvan0212** [comment]
I did remove case-sensitive from sorting.

**Comment by arlin** [comment]
Thanks!  Closing.
