### ISSUE TITLE
option to hide internal node names

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#160]
In ETE, displaying internal node names causes the tree to become very wide, e.g., look at the ants tree from https://en.wikipedia.org/wiki/Ant.  

Implement an option to show internal node names.  Turn this option *off* by default.  

Alternatively, turn this option *off* whenever there are more than 20 OTUs in the tree.

**Comment by abusalehmdtayeen** [comment]
This feature is done.  User can turn on/off show internal node names feature.

**Comment by arlin** [comment]
Great!  We just need to change the label.  

Change "Show internal nodes" to "Show node labels".

**Comment by ducvan0212** [comment]
I changed to "Show node labels", @arlin

**Comment by arlin** [comment]
thanks, closing this.
