### ISSUE TITLE
find out why this doesn't work

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#162]
One of our use-cases is to create a clickable resource to aid in exploring the flora of national parks, based on this web site:

https://www.usbg.gov/floraofthenationalparks

This page can't be scraped directly due to dynamic content.  So, I copied and pasted the table into Excel, extracted out the column of species, and put this in the following: 

 https://github.com/phylotastic/phylotastic-portal/blob/master/interactive_test/Extract_from_List/park_svc_usecase2.txt

This list is not processed due to some error.  @ducvan thinks it is due to a special character.

**Comment by arlin** [comment]
I just retested the file, and I still get the same error. If you are not getting an error, then I suspect there was some change in text encoding when the file was transferred to github and then downloaded. I will email you a zipped version of the file so that no conversion takes place.

**Comment by ducvan0212** [comment]
I generated a link to your uploaded file in server. 
http://phylo.cs.nmsu.edu:3000/system/onpl_files/documents/000/000/085/original/park_svc_usecase2.txt

You can see "Â" symbol in the file but if you download the file and open it in a text editor.

**Comment by ducvan0212** [comment]
Because the file can not be read so it is put into the waiting queue in background job. That is the reason why you saw only a loading leaf instead of a full species list.

**Comment by ducvan0212** [comment]
<img width="209" alt="screen shot 2016-09-21 at 4 29 40 pm" src="https://cloud.githubusercontent.com/assets/1614884/18731353/a98d728a-8018-11e6-8091-ae65df78a4af.png">

@arlin I found another "Â" symbol. After removing these 2 line which contains "Â" symbol, I can get the list normally.

**Comment by ducvan0212** [comment]
@arlin I replaced malicious symbol in file with "?" before extracting names. It should work now.

**Comment by arlin** [comment]
@ducvan0212, there is no way for me to delete jobs that are hung.  The "delete" button does not appear, only the waving leaf icon.

**Comment by arlin** [comment]
@ducvan0212, what should we do about this?   I would suggest: 

* replacing malicious symbol with ?? then processing, so that this comes out as a non-matched name rather than an error
* warning user that a symbol was replaced and asking them to check the FAQ
* putting some information in the FAQ about this problem  "Sometimes web pages and other sources have hidden characters or other non-ASCII characters that foul up processing.  This stackoverflow thread [http://stackoverflow.com/questions/3001177/how-do-i-grep-for-all-non-ascii-characters-in-unix] explains how to identify and expose such characters."

**Comment by ducvan0212** [comment]
I automatically replaced maliciouse symbol with '?' and added delete button when a file could not be processed.

**Comment by ducvan0212** [comment]
After moving FAQ to Help page, I also add information about  non-ASCII characters in "Why is my species not found?" section

**Comment by arlin** [comment]
Good work.  thanks.
