### ISSUE TITLE
failure to extract names from web site

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#164]
One of our use-cases calls for creating a phylogenetic guide from natural language queries such as "birds of papua new guinea".  The top hit for this on google is 

https://en.wikipedia.org/wiki/List_of_birds_of_Papua_New_Guinea 

I know that this page has about 900 valid species names, because I have processed it directly with GNRD.  However, the portal does not process this list using the "Extract from Web" workflow.  

Is this a bug, or does this hit some kind of limit on the number of species?

**Comment by abusalehmdtayeen** [comment]
@arlin, I checked the url with our find names web service. It gives result of 912 species within 7 secs. I think the problem is on the portal end. @ducvan0212 , can you check?

**Comment by ducvan0212** [comment]
@arlin @abusalehmdtayeen I created tree with your link. What is the error you got?

**Comment by arlin** [comment]
I do not get an error.  I just get this, forever: 

<img width="597" alt="screen shot 2016-09-21 at 6 04 49 pm" src="https://cloud.githubusercontent.com/assets/1659198/18730763/021d9936-8026-11e6-83f3-d295b28208aa.png">

**Comment by arlin** [comment]
I just retested the file, and I still get the same error.  If you are not getting an error, then I suspect there was some change in text encoding when the file was transferred to github and then downloaded.   I will email you a zipped version of the file so that no conversion takes place.

**Comment by ducvan0212** [comment]
Let make it clear, I tried to use https://en.wikipedia.org/wiki/List_of_birds_of_Papua_New_Guinea and I could create tree from this link

I checked "Aquatic vs. terrestrial plants" file and I saw a species named
OpuntiaÂ sp.

<img width="217" alt="screen shot 2016-09-21 at 4 14 14 pm" src="https://cloud.githubusercontent.com/assets/1614884/18731017/97757860-8016-11e6-9d04-095343a0db5c.png">

It caused file reader corrupted. But in text editor, I can not see the "Â" symbol.

**Comment by arlin** [comment]
I think we are mixing up some tickets here.  

I retried the birds list.  This time, I was able to get a list.  Maybe I didn't wait long enough?  

So, I am going to close this ticket.
