### ISSUE TITLE
Bigger text throughout

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#168]

**Comment by ducvan0212** [comment]
<img width="1128" alt="screen shot 2016-09-25 at 10 38 23 am" src="https://cloud.githubusercontent.com/assets/1614884/18816729/64954c24-830c-11e6-9324-4de4896bb928.png">

Side-by-side comparison between before and after increasing text size

**Comment by arlin** [comment]
That is an improvement, but I would like to see bigger text for all fixed UI elements.  User data such as the name "Leporidae" could be the current size, but none of the menu items or buttons should be smaller than the size used for "My Lists".   

Also, it might help to use a different font for user data vs. fixed UI controls.

**Comment by arlin** [comment]
Again, emphasize "My Lists", "Public Lists", "Welcome to Phylotastic" and so on because these are titles or headers for key interface elements.

**Comment by arlin** [comment]
Thanks, you just fixed most of this, @ducvan0212.   The only thing that needs to be changed is "MAKE A NEW LIST \n Choose from source" .   Please 
* remove the "Choose from source" 
* change "MAKE A NEW LIST" to "Make a New List" (consistent with other titles)
* use the larger font for "Make a New List"

then we're done with this one, too.

**Comment by arlin** [comment]
Thanks, it looks good.
