### ISSUE TITLE
fixes to About page

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#171]
* give info on all contributors
* add group photo
* credit NSF grant for each center
* list of services and sources we depend on 
   * OT
   * EOL
   * GNRD
   * iNaturalist
   * others?

**Comment by arlin** [comment]
group photo is in portal/design/images

**Comment by arlin** [comment]
I made a draft of this.  @hdliv can you review this?  it still needs more work.

**Comment by hdliv** [comment]
@arlin where is the draft?

**Comment by hdliv** [comment]
@arlin nevermind.  I was looking for it in the repository and not directly on the webportal.

**Comment by arlin** [comment]
@ducvan0212, can you look at this and figure out why the group photo doesn't load?  I tested the relative path so that is not the issue.  Possibly the application framework prevents loading content from arbitrary locations as a security precaution.

**Comment by ducvan0212** [comment]
The image is displayed in About page :-)

**Comment by arlin** [comment]
Thanks, yes I see the image now.  You had to put it in "assets"?

**Comment by ducvan0212** [comment]
You have to put the image in public/images and add assets in image path. The only resources can be accessed from outside word is public.
