### ISSUE TITLE
submit node-actions menu bug to ETE

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#177]
node actions menu is often compressed horizontally and is placed away from node.  There is no graphical indication of which node is implicated by the menu.  

This is an ETE bug, so we need to bring it to the attention of ETE and suggest some solutions: 
* fix horizontal compression
* indicate implicated node.  Ideas
   * display node name (if present) at top of menu, e.g., "actions for node 'Mammalia'" 
   * highlight the node with blinking or pulsing dot
   * indicate the node with line connector or triangle connector to menu

**Comment by abusalehmdtayeen** [comment]
I think it is fixed now. The menu now appears near the node and node name is displayed along with the actions of the menu.

**Comment by arlin** [comment]
thanks, closing this.
