### ISSUE TITLE
tree view hints

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#178]
On tree view, provide explanation to user. 

"Click on a name or a node to see viewer options.  More info is available in the "Tree Viewer" section of Help. "

this is not the same as #179 (tree viewer instructions in Help menu)

Another way to do this is to have a pop-up with the above message when the user selects the tree view.  This should have a box that says "Got it.  Don't show me this message again".  If the user clicks the box, don't show the pop-up again.

**Comment by ducvan0212** [comment]
Maybe user will misclick and thus unable to see the message again so I made the popup displays when user first sign in. Whenever user selects a tree to view within his/her first sign in, the pop up is shown up. In the next sign in, the message will disappear.

**Comment by arlin** [comment]
I am not able to access this.  I signed out and signed in again, but I did not see it.

**Comment by ducvan0212** [comment]
I reset your login_count for your account. Can you try again?

**Comment by arlin** [comment]
Yes, thanks, it works!  I'm worried that users will find this annoying.  It pops up every time I view a tree, even if I don't leave the Tree View.   Can you reset everyone's account so that we can get more feedback on this?

**Comment by arlin** [comment]
![screen shot 2016-09-28 at 11 00 54 am](https://cloud.githubusercontent.com/assets/1659198/18919323/a7feffbc-856b-11e6-8e01-f17c333f577f.png)

**Comment by ducvan0212** [comment]
I made the pop up smaller and reset all account.

**Comment by arlin** [comment]
I don't like this.  I saw this pop-up 6 or 7 times until I got tired of seeing it and ended my session.  It comes up every time I view another tree.  Please just allow the user to dismiss it with one click rather than tying it to the session.

**Comment by ducvan0212** [comment]
@arlin I reworked on this. Can you check again?

**Comment by arlin** [comment]
I can test anything right now.  The tree viewer does not work.  "Export" shows that the portal knows about the tree, but there is no image, and no capacity to download png or svg.  This means that the ETE part is not working.  

![screen shot 2016-10-03 at 3 54 56 pm](https://cloud.githubusercontent.com/assets/1659198/19051744/0b049aa8-8982-11e6-9fc3-248a0666e762.png)

**Comment by abusalehmdtayeen** [comment]
@arlin, I checked the ETE web service and it  is running properly. I also tried to use the portal while keeping an eye on the web service request log, but it seems the portal is not sending any request to the service when a user is clicking on get tree button or selecting any saved tree. @ducvan0212 , can you check your end?  Specially the part where we made modification about the treeid.

**Comment by ducvan0212** [comment]
@arlin @abusalehmdtayeen It is because the server is not up-to-dated with changes made in tree visualization. I updated the portal so no more tree rendering error

**Comment by arlin** [comment]
@ducvan0212, earlier you said that you re-worked this feature, but I don't see a difference.  What is different?  I think you might need to reset my session count again.

**Comment by arlin** [comment]
During a user test today, I noticed that this is working as requested.  Thanks.  Closing.
