### ISSUE TITLE
add tree viewer instructions to Help

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#179]
In the help section on the tree view, explain the tree viewer options.  

* branch lengths
* branch width
* images
* zoom
* node actions (highlight, EOL, etc)

**Comment by arlin** [comment]
This still needs to explain problems with controlling the zoom, unless we fix those.

**Comment by arlin** [comment]
also, needs to explain that the "node labels" are often useful taxonomic names, but we turn them off by default.

**Comment by arlin** [comment]
I worked on this yesterday.  @hdliv can you review and see if the instructions are sufficient?

**Comment by hdliv** [comment]
@arlin I think so -- closing ticket
