### ISSUE TITLE
Save tree-viz customizations

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#182]
Portal saves tree viz annotations and modifications internally, so that they are not lost when user navigates away from tree. 

This can be done by saving the ETE commands.

**Comment by abusalehmdtayeen** [comment]
@arlin @hdliv  This feature is complete in dev server. Now user will be able to save the last state of the tree and load it again in the same state after he moved on to a different tree.

**Comment by arlin** [comment]
thanks, this is great functionality @abusalehmdtayeen !   we need to rethink the UI choices however.  i think the user is going to expect that tree state will be saved by default and loaded again by default.  Probably the only option we need is a "remove customizations" button in case the user wants to return the tree to its unadorned state.  

Anyway, let's talk about it tomorrow.  Good work.

**Comment by hdliv** [comment]
@abusalehmdtayeen this is fantastic!

**Comment by arlin** [comment]
OK, this is all fixed.  Good work.  Sorry for not closing this sooner.
