### ISSUE TITLE
remove login wall

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#185]
I thought we fixed this, but apparently not.  A new user must be able to evaluate our products without signing in.  Currently the only actions available to the user involve viewing a public list along with its taxon matching report. 

Choosing to view a tree for a public list is not allowed.  Choosing one of the Make a New List options is not allowed.  This means that users currently cannot evaluate anything interesting about Phylotastic without signing in. 

In the web development world, this is called a "login wall".  Login walls should be avoided unless they provide a real benefit to the user: 

https://www.nngroup.com/articles/login-walls/

We really, really need to fix this before a wide release.  The login wall will discourage many potential users.   

The way to fix this is called "session management."  When the user first visits, you establish a session ID that allows the web app to identify an anonymous user by session.  Because HTTP is stateless, you have to pass this ID with every request.  The session can be continued after the user authenticates.  See https://www.owasp.org/index.php/Session_Management_Cheat_Sheet.

**Comment by ducvan0212** [comment]
I can allow anonymous user create a tree from public list. Because this feature is not in design so the system will only allow to upload files, links, documents WITH user's identity.  User's identity involves in inside logic operations of portal, not just session management so it actually a complex problem.

**Comment by ducvan0212** [comment]
Except uploading DwC-A requires user identity, all other workflows now expose to anonymous users.

**Comment by arlin** [comment]
@ducvan0212, trees made by anonymous user seem to go into Public Trees list, where they are accessible to others, then disappear when session is over.  Is this the intended behavior?

**Comment by ducvan0212** [comment]
I keep the tree in Public Trees list. It will not be removed anyway.
