### ISSUE TITLE
Improve public list choices

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#186]
I'd like to improve the titles and content of the public lists.  

* make sure "Leporidae" is not the first choice (major polytomies, mostly taxonomy)
* change "Lesson on the" to "(lesson)"
* fill out the "Description" metadata fully, especially for the ones marked "(lesson)"

For instance, consider "(lesson) Marine and Terrestrial Mammals".  I would rename this "(lesson) Mammals returned to the sea repeatedly" and describe this story in the "Description" field so that teachers can use it.  The description should use plain language, and may include questions like "How many times did aquatic mammals evolve?" or "What is the relationship of birds and mammals to reptiles?"

**Comment by hdliv** [comment]
@arlin I have other public lists that I will add.  Do you suggest any in particular?

**Comment by arlin** [comment]
Make sure we have multiple lists that will appeal to a wide audience including non-researchers.  The titles of these should not contain technical terms.  "Mammals returned to the water 3 times" is better than "Aquatic vs. terrestrial mammals".    

I think some of these lists can do double-duty as educational examples . We just need to fill out the descriptions more fully.  I can work with you on that.

**Comment by arlin** [comment]
This might be a good source because it focuses on the key groups of mammals necessary to show changes in thinking about relationships over the past 20 years.  http://blogs.scientificamerican.com/tetrapod-zoology/refined-fine-tuned-placental-mammal-family-tree/

**Comment by hdliv** [comment]
for some reason the descriptions are not showing up when I add the public lists

**Comment by arlin** [comment]
@hdliv, the lists look good.  Thanks.  We were going to upload them with underscores in front to be sure that they sort to the top.  Do you think that is necessary?  I don't think so.   We are the only people making public lists right now, so it isn't as though this is going to fill up with junk that is out of our control. 

If you decide that isn't necessary, then please move this ticket to review.

**Comment by hdliv** [comment]
i dont think it is necessary.  we might just add one more example of edible seaweeds, but I will close this issue since we already have nice examples

**Comment by arlin** [comment]
OK, I'm closing this.  Good work @hdliv
