### ISSUE TITLE
'Download selected species as list' to 'Download selected taxa as list'

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#188]
In the Home view, change the name of the tab from "Download selected species as list" to  "Download selected taxa as list".

**Comment by arlin** [comment]
This hasn't changed. 

<img width="226" alt="screen shot 2016-09-28 at 4 06 53 pm" src="https://cloud.githubusercontent.com/assets/1659198/18930354/b82bb770-8595-11e6-98fa-7e67202e0660.png">

**Comment by ducvan0212** [comment]
Can you check again, @arlin

**Comment by arlin** [comment]
OK, good.  thanks.
