### ISSUE TITLE
accordion bizarreness on Help page

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#190]
Open or reload Help.  The "Guide" panels are all open, and the "FAQ" panels are all closed.  Good.  This is what we want.  

Now, open an FAQ panel.  The "Guide" panels all close.  

Why does this happen?  Do we want this?  

Possibly I screwed up the accordion labels in some way.  I don't understand the system.  

This is a very small annoyance, not urgent.

**Comment by ducvan0212** [comment]
I fixed it for you, @arlin :-)

**Comment by hdliv** [comment]
@arlin  @ducvan0212 got to it before me.  thanks for being quick. moving ticket to In Review

**Comment by arlin** [comment]
This is fixed.  Thanks.
