### ISSUE TITLE
accordion styling too subtle

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#191]
Please turn up the contrast in bkg color between the panel title (very light grey) and panel body (white) in the Help accordion.  The distinction is so subtle that it completely disappears when viewed on one of my displays-- title and body both look white and it is difficult to navigate without being able to distinguish them.

**Comment by ducvan0212** [comment]
Can you check that the new color for Help headings is dark enough?

**Comment by arlin** [comment]
closing this. thanks.

**Comment by arlin** [comment]
In the future, please do *not* take issues off of the backlog.  We have backlog for a reason-- to create a distinction between issues that are an immediate priority for action, and issues that are not.
