### ISSUE TITLE
provide supporting studies for subtree

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#193]
As discussed at f2f meeting, we want to provide a list of supporting studies with the return subtree from OT.  This supports  important use cases for researchers, namely (1) I'm using phylotastic to expose the literature on a set of relationships and (2) I want to see if my published study is implicated.  

@jar398 says "Looking at the code, it does seem there's a "supporting_studies" list in the returned result. So I think the feature you just requested is already there. If it's buggy let me know."

So, this may be easier than we thought.

**Comment by abusalehmdtayeen** [comment]
Actually they have added this "supporting_studies" property in version 3 of their API. We need a separate web service to get the studies information. I am working on that.

**Comment by arlin** [comment]
good, I'm looking forward to it.  this will be valuable for our users.

**Comment by jar398** [comment]
See https://github.com/OpenTreeOfLife/germinator/issues/89

**Comment by abusalehmdtayeen** [comment]
Web service description added. https://github.com/phylotastic/phylo_services_docs/blob/master/ServiceDescription/PhyloServicesDescription.md#web-service-17

**Comment by ducvan0212** [comment]
@hdliv where should I add this information in the portal?

**Comment by hdliv** [comment]
@ducvan0212 we need to discuss this

**Comment by ducvan0212** [comment]
@hdliv I am ready

**Comment by hdliv** [comment]
@ducvan0212 .   @arlin and I will go over a suggestion to show all metadata, and come back to you

**Comment by arlin** [comment]
Thanks @hdliv @ducvan0212 @abusalehmdtayeen for getting this done.  This is a valuable feature for users.
