### ISSUE TITLE
graphic for welcome pane

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#195]
the "welcome" pane shown to a new user would benefit from a graphic illustrating the workflow and perhaps some terms.  

![graphic](https://cloud.githubusercontent.com/assets/1659198/19198129/6e00fc8a-8c8b-11e6-8d4e-41c52ca3d8ee.jpg)

**Comment by arlin** [comment]
I generated a graphic and put it in app/assets/images.  @ducvan0212, can you make this part of the welcome message?  

![welcome](https://cloud.githubusercontent.com/assets/1659198/19199413/eddbd5c8-8c91-11e6-8c94-9fd902644bc4.png)

**Comment by ducvan0212** [comment]
That is a very nice image. I inserted it into welcome message. Thank you, Arlin.

**Comment by arlin** [comment]
Can you put a light frame around this, please?  This will graphically separate the labels at the top of the image from the text above it.  Currently this is visually confusing.
