### ISSUE TITLE
notify user upon view failure

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#198]
Currently there is no notification upon viewer failure.  In a user test, the user followed this up by pressing the "Generate image link" button.  

1.  Test for viewer failure
2.  Notify the user with an alert box.  See the message below.  The alert box should have a button for "close" and a button for "Send feedback" which goes to the feedback form.  

Message: "Sorry!  We got a tree (click "Export") but there was an error trying to view it.  Try another tree, and use "Feedback" to report any errors."

<img width="1097" alt="screen shot 2016-10-12 at 4 54 57 pm" src="https://cloud.githubusercontent.com/assets/1659198/19327430/057773d6-909d-11e6-880a-b78fe6f3c463.png">

**Comment by ducvan0212** [comment]
I will keep a error in development server so you can see the pop up. I will remove the error when this ticket is closed.

**Comment by ducvan0212** [comment]
@arlin can you see the pop up when you open a tree in tree viewer?
<img width="638" alt="screen shot 2016-10-19 at 2 19 48 pm" src="https://cloud.githubusercontent.com/assets/1614884/19535982/3a323d76-9607-11e6-8803-de020746eeec.png">

**Comment by arlin** [comment]
Yes.  You can remove this now.
