### ISSUE TITLE
list download failure

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#200]
download list failure - unexplained bug
* go to Home
* select Birds vs Reptiles 
* try "Download .." --> WORKS
* click "Select/Deselect all" to deselect all
* click "Select/Deselect all" to select all
* try "Download .." --> FAILS

**Comment by ducvan0212** [comment]
@arlin can you check that this error is fixed in development server?

**Comment by arlin** [comment]
yes, this is fixed in dev.  thanks.
