### ISSUE TITLE
relocate "Get Tree" button, etc

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#205]
Make the following changes.  

1. remove current "Get tree" 
2. add "List viewer" as title to center panel, using same font as "Public lists"
3. add "List actions" as title for the lower right list
4. add "Get tree" to the "List actions" menu
5. swap the two lists on the right: put “List actions” above, “Make a new list” below”
6. rename "Download selected species as text" to "Download list"

![list_view](https://cloud.githubusercontent.com/assets/1659198/19368132/91e2f488-916c-11e6-8ea2-bd6eaa8ec697.png)

**Comment by ducvan0212** [comment]
I made changes as you suggested, Dr. Arlin.

**Comment by arlin** [comment]
Thanks.   Please use sentence capitalization throughout the portal interface, as indicated in the image above.  This means that only the first letter of the first word is capitalized, unless there is a capitalized name like "EOL" in the phrase.  Sentence capitalization: The origin of species.  Title capitalization: The Origin of Species.  

There will be additional changes to this view after we finish processing the user tests.

**Comment by arlin** [comment]
There is already a separate ticket calling for sentence capitalization, so I'm going to close this.
