### ISSUE TITLE
Lost list in anonymous mode

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#207]
Extract from web in anonymous mode.  This creates a list.  Click on Tree view, then back to List view.  List is gone because there is no way to save.  

This is part of the "login wall" we are trying to eliminate. It must be possible for the anonymous user to have > 1 list and to return to view lists.

**Comment by ducvan0212** [comment]
@arlin I pushed my work on the server. Now, anonymous users can see their lists.

**Comment by arlin** [comment]
Thanks.  The dev server is down now, but I used this feature earlier today so I know it works.
