### ISSUE TITLE
Test browers

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#208]
Test portal with all 4 browsers: chrome, firefox, safari and IE.  Once these tests are done, we can push the latest updates to production.

**Comment by arlin** [comment]
we are testing IE today.

**Comment by arlin** [comment]
We have tested all 4 browsers.  We did a quick job with IE and did not go into great detail, because things seem to be working just fine.  The only issue was with the usual PC-Mac-UN*X line-ending incompatibility .
