### ISSUE TITLE
tree feedback to user

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#209]
Get tree feedback: report to user how many taxa were found

**Comment by ducvan0212** [comment]
Can you provide more description on this issue?

**Comment by arlin** [comment]
"Feedback" means providing information to the user about what the app is doing in response to the user's action. See:

 http://www.designforfounders.com/web-app-ux/ 

For instance, in Waffle, if you mouse over the "209" in the top left of this ticket, it changes color, which tells the user that there is some mouse-activated action associated with "209".  

Here we are asking for feedback on how many species from the user's query were found.  This feature has been requested by 2 users.  For instance, the user might submit a list with 15 names, and get a tree with 12 tips.   One way to provide feedback is to have a pop-up that says "A tree with 12 species was extracted (out of 15 names in query list)" with an "OK" (dismiss) button.

**Comment by arlin** [comment]
Thanks.  this is currently working.  

<img width="474" alt="screen shot 2016-10-19 at 4 31 18 pm" src="https://cloud.githubusercontent.com/assets/1659198/19536336/92b1a45c-9619-11e6-9cf6-91754a23d734.png">

**Comment by arlin** [comment]
@ducvan0212, are you done with this one?

**Comment by ducvan0212** [comment]
I am checking on this issue. Please wait a little bit.

**Comment by ducvan0212** [comment]
@arlin To generate message in the pop up, I counted all names shown in the tree newick format. In your case is 152 species. It is not the number of species in tips of tree. Do this meet your expectation?

**Comment by ducvan0212** [comment]
There are some names in middle nodes of trees.

**Comment by ducvan0212** [comment]
I counted species chosen by user, not actual number of species in tree tips. I am not sure how to count the actual number in tree newick format but I will require more process time

**Comment by arlin** [comment]
I think the formula would be to add the number of commas and left parens.  Anything preceded by a comma or a left paren is a tip.   Another way to do this is to just import some library like DendroPy, and use existing functions.

**Comment by arlin** [comment]
The number of tips is left parens + commas.  Most people will be interested in the tips.  However, if the list contains the name of a genus, and the name of a species in the genus, it may include both names, or it may include only the species name.  

I think the way to do is to report 2 things: the number of tips, and the match of OTT ids between the query and the tree.  You can extract the OTT Ids from the tree and match that them with the input list.  

Then report "Retrieved a tree with XX tips.  YY of ZZ taxa in the input list were matched", where ZZ is the entire list of OTT Ids in the query, and YY is the number (out of ZZ) that are in the tree.

**Comment by ducvan0212** [comment]
@arlin I shut down the server to install a library to parse newick. Can you check this issue?

**Comment by arlin** [comment]
That is an improvement, but the language needs to be fixed.  The matched names are not necessarily "species".  Change this to "Retrieved a tree with 53 tips.  68 of 83 taxa in the input list were matched."

![screen shot 2016-10-20 at 3 14 49 pm](https://cloud.githubusercontent.com/assets/1659198/19574424/3fbaf68a-96d8-11e6-9b39-b976915a642c.png)
