### ISSUE TITLE
develop plan to discover requirements

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#21]
Develop a plan to identify use-cases (working with stakeholders), and extract requirements for the generalized web UI.

**Comment by arlin** [comment]
Dail, please put your plan in the phylotastic/phylotastic repo and close this issue.  Use a generic description of the plan without any names of people (no names in the public repo).

**Comment by hdliv** [comment]
Plan of action:
	Create new use-cases with information from the community
              - develop requirements of all of the use-cases gathered
       To get this variety of use-cases that are representative of what the end user wants/needs, the community will be contacted
       - Who are the end- users? they are  Scientists, Curators, general public and educators
       - With the feedback from the community, create use-cases. 
       - The 'community' consists of 
              -scientists and curators of all biodiveristy
              -Educators: middle & high school teachers and general bio lecturers
              -the general public are people in federal/state/private positions that can benefit from a phylotastic system & general public interested in understanding relationships of entities across the ToL

**Comment by hdliv** [comment]
The initial e-mail has gone to 22 potential users

**Comment by arlin** [comment]
Dail, when you are done putting a write-up of your plan in github (probably somewhere in phylotastic-portal), then you can move this ticket into "Review"

**Comment by hdliv** [comment]
under design in the portal
closing ticket
