### ISSUE TITLE
Edits on 'Choose from taxon'

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#210]
* Choose from taxon - embedded docs and styling
  * change black "(\*)" to red "\*"
  * change prompt from "Taxon name" to "Taxon name (mouse-over for important instructions)" 
  * add mouse-over text that applies both to Taxon name prompt and to input box: "Tax
  * greyed-out text in Taxon name: "e.g., Canidae, Felidae, Balaenoptera"
  * change "Subset by" to *boldfont* "Subset (choose one)" 
  * double the size of the click-boxes
  * remove bold font from "Has genome sequence in NCBI"
  * change "Has genome sequence in NCBI" to "by known genomes"
  * change "Location" to "by country"
  * change "Random subset of" to "at random"

**Comment by ducvan0212** [comment]
I need full text for the prompt in the third item

**Comment by arlin** [comment]
Sorry, we forgot to finish that message.  "Enter the scientific name of a taxonomic group such as a genus, family or order.   See the FAQ for how to find scientific names.   You may choose only one taxon.  When subsetting by NCBI genome, queries using large taxa are possible. Otherwise, we can't process queries on taxa with more than  a few hundred species. "

**Comment by arlin** [comment]
Greyed-out text needs to begin with "e.g., " otherwise the user will think that it is possible to enter a comma-separated list of 3 taxa.

**Comment by arlin** [comment]
Also, can you set the default country to something other than Albania?   What about Brazil or United States?  There are also ways to generate a random default value (look it up on stackoverflow).

**Comment by ducvan0212** [comment]
Of course it can be set to a default country. I will set default value to United States, Dr. Arlin.

**Comment by ducvan0212** [comment]
@arlin I made changes and moved this ticket to preview but I have not pushed anythings to dev server yet. I will work on some other tickets first then push everything to server in one request so please dont check now. Thank you, Dr. Arlin.

**Comment by arlin** [comment]
Good work, @ducvan0212.  Thanks.
