### ISSUE TITLE
leaf-node actions

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#212]
* changes to leaf-node actions
  * fonts
     * enlarge by 2 points
     * title in bold, others not in bold
  * title: "Medicago sativa" actions (use leaf name)
  * item 1 (EOL link): "Read info page"
  * items 2 to 4 should be toggles 
  * item 2: "Add (remove) photo"
  * item 3: "Add (remove) box"
  * item 4: "Thick (thin) branch"

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I checked in style sheet file but there is no css rule for these changes. I guess you generated css and html elements dynamically. Can you check again?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , yes the leaf actions are generated dynamically. I will take care of this issue.

**Comment by abusalehmdtayeen** [comment]
@arlin @hdliv , this feature is done. Please check in the development instance of portal.

**Comment by arlin** [comment]
@abusalehmdtayeen, please change the title from  "Actions menu" to "'LeafName' actions" as requested.  

![screen shot 2016-10-20 at 3 04 39 pm](https://cloud.githubusercontent.com/assets/1659198/19574146/01719ef2-96d7-11e6-8886-1ec62216f47a.png)

**Comment by abusalehmdtayeen** [comment]
@arlin , title has been changed.

**Comment by arlin** [comment]
better, but the italics disappeared. NodeName has to be distinct from "actions".  

![screen shot 2016-10-20 at 3 49 51 pm](https://cloud.githubusercontent.com/assets/1659198/19575546/06a12b30-96dd-11e6-85c0-9bfc126c9980.png)
