### ISSUE TITLE
internal node actions

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#213]
* changes to internal node actions
  * fonts
     * enlarge by 2 points
     * title in bold, others not in bold
  * title: 
     * named: Node "Node name" actions 
     * un-named: Node actions
  * item 1: "Collapse subtree"
  * item 2: "Rotate subtree"
  * item 3: "Add (remove) box"
  * item 4: "Thick (thin) branches"

**Comment by ducvan0212** [comment]
@abusalehmdtayeen same as #212.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , I will take care of this issue.

**Comment by abusalehmdtayeen** [comment]
@arlin @hdliv , this feature is done. Please check in the development instance of portal.

**Comment by arlin** [comment]
@abusalehmdtayeen, please change the title from  "Actions menu" to "'NodeName' actions" for a named node, or "Node actions" for an un-named node.  

![screen shot 2016-10-20 at 3 06 02 pm](https://cloud.githubusercontent.com/assets/1659198/19574237/65978978-96d7-11e6-8f9d-e70536e847a6.png)

**Comment by abusalehmdtayeen** [comment]
@arlin, title has been changed.

**Comment by arlin** [comment]
same comment as for #212
