### ISSUE TITLE
Public tree list full of junk from anonymous users

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#214]
Trees made by anonymous users seem to go into the public tree list.  This means that, when new users look at the list, they are looking at junk from new users, often with meaningless titles.  This is confusing.  

We need to populate the public trees list with some nice examples.  If we assign them names beginning with space or underscore, they will sort to the top of the list.  That is a temporary fix.  A better fix would be to store temporary anonymous trees somewhere else.  

![screen shot 2016-10-17 at 4 13 31 pm](https://cloud.githubusercontent.com/assets/1659198/19453886/0d096794-9485-11e6-84f1-4b56b4fcfa25.png)

**Comment by ducvan0212** [comment]
Trees made by an anonymous user will not be put in public category anymore.

**Comment by arlin** [comment]
@ducvan0212, anonymous tree creation is now broken, at least for me.    Log out.  Choose "Extract from web" with https://en.wikipedia.org/wiki/Wombat.  Choose "Get tree" .   This is what I see:

**Comment by arlin** [comment]
I'm making this ticket a priority now.  I assume that this is the one that broke anonymous tree creation.  However, perhaps  the routing is broken due to the new alert message.

**Comment by ducvan0212** [comment]
Yes, I am testing so I turned this off.

**Comment by ducvan0212** [comment]
I turned it back. But please check #209

**Comment by arlin** [comment]
@ducvan0212, public tree list on production is still full of junk.  @hdliv and I did testing today and we identified this as a critical issue to fix.  New users will inspect this list hoping to find something useful to examine, and they will be confused or disappointed.  We don't want to confuse or disappoint new users.  

1.  remove all of the trees currently in the Public Trees list on production
2.  implement a way for logged-in users to make a tree public

Once you have done that, Dail and I can upload a set of useful trees for people.

**Comment by ducvan0212** [comment]
@arlin @hdliv  Would you mind if I reset database in production server?

**Comment by arlin** [comment]
I don’t mind 

On Oct 25, 2016, at 5:30 PM, ndvan <notifications@github.com> wrote:

> @arlin @hdliv Would you mind if I reset database in production server?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------------
Arlin Stoltzfus (arlin@umd.edu)
Research Biologist, NIST; Fellow, IBBR; Adj. Assoc. Prof., UMCP
IBBR, 9600 Gudelsky Drive, Rockville, MD, 20850
tel: 240 314 6208; web: www.molevol.org

**Comment by hdliv** [comment]
that is fine with me

**Comment by arlin** [comment]
OK, list has been cleaned out.  I'm closing this.  Now, let's try to get 2 or 3 usable trees in there.
