### ISSUE TITLE
How do we get more eyes on Help?

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#215]
Users frequently do not click on "Help" until very late in the session, e.g., after 10 or 20 minutes.  Why don't users look at Help?  What might change the flow so that they notice this sooner?  

Examine other web sites to see what they do, and make a suggestion.  

One possibility would be to emphasize the top bar visually, and reduce it to "Home", "Trees", and "More", where "More" has a submenu for Help, About and Feedback.  

Another possibility: put Help at the far right.  Perhaps the middle positions of the menu bar are the least noticeable.

**Comment by arlin** [comment]
Maybe this is a good thing?  Users don't click Help because they are getting along fine without any explicit instructions.

**Comment by hdliv** [comment]
@arlin I think people usually go to 'Help' as last resort if they are not able to figure portals alone

We can ask those that are looking at the webportal in this initial release to see what they think
