### ISSUE TITLE
non-standard behavior of node actions box

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#216]
Select a node to get the node-actions box.  
* click outside the viewer area --> nothing happens (as expected)
* click inside the viewer area --> box jumps to new location 

The second one is not expected behavior.  Clicking outside the box should close it, not move it.

**Comment by arlin** [comment]
This is important to fix because it confuses users-- we have often been confused by this in the past.  We click on a node, and a box appears.  Then we try to click on another node. However, often it is difficult to select the node with the mouse, and this fails.  This ought to make the box disappear.  However, the box appears in a new place close to the mouse-down event.  This tricks the user into thinking that a new node has been selected, when actually it has not.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I think we should work together to resolve ETE user-interface/user experience tickets. Because js code in ete is derived from multiple auto-generated parts so if you spot them then I fixed, it would be quicker.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , you are right. We have to work on these issues together. I will email you about scheduling a meeting time.

**Comment by ducvan0212** [comment]
In development server, the popup is closed when you click on parts that are not nodes of tree

**Comment by arlin** [comment]
Thanks, this is a big improvement :-)
