### ISSUE TITLE
polling for status of tree

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#22]
Automatically poll to web server in a interval of 10 seconds to get status of trees which have not had status "completed" yet. There are also buttons to check status manually

**Comment by arlin** [comment]
pool = poll?

**Comment by ducvan0212** [comment]
I fixed it. Thank you, Professor.

**Comment by arlin** [comment]
This feature seems to be working, but it is difficult to tell.  Most operations either resolve quickly or get stuck and take a long time.
