### ISSUE TITLE
redesign OTT ID option for Newick output

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#222]
Users are currently confused.  Button is labeled "Export as TXT" with pulldown options "WITH ottids" and "WITHOUT ottids".  User is not sure whether this is the same as the download button, and does not know what OTT Ids are.  User says "I like what I see [the Newick string] but I don't know if it has the IDs or not".  

1.  Add check box to include OpenTree IDs.  When user clicks, Newick string is replaced. This gives the user feedback on what the IDs look like.  Add a float-over that says "Include the IDs used internally by the OpenTree project". 

2. Remove the pull-down options, and change "Export as TXT" to "Save".

**Comment by ducvan0212** [comment]
I did make this change, Dr Arlin

**Comment by arlin** [comment]
Thanks.  This is much easier for the user to understand!  Closing.
