### ISSUE TITLE
fix tip alignment on trees

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#226]
Search "phylogeny" on google and click "images".  For square trees, the branches typically extend out to the tip labels.  This is what our users expect.  Currently our tree view shows uniform branch lengths that do not extend out to the tip labels.

![image](https://cloud.githubusercontent.com/assets/1659198/19459915/c93a10ac-94a4-11e6-8821-90f94fd8007f.png)

![image](https://cloud.githubusercontent.com/assets/1659198/19459920/d6330cbe-94a4-11e6-8cd7-04aacf949e9d.png)

![image](https://cloud.githubusercontent.com/assets/1659198/19459933/f5515a74-94a4-11e6-9ee4-50522cc7fc15.png)

**Comment by abusalehmdtayeen** [comment]
@arlin , Currently there are dotted lines that extend to the tips from branches. Will making the dotted line to solid lines solve this issue? Or do you mean something else?

**Comment by arlin** [comment]
@abusalehmdtayeen, it doesn't sound like a good solution, but I'll let you figure that out.  

The "look" that we want for our trees is illustrated in the examples above.  The tree must consist of straight solid lines that extend to the tip labels.  The appearance of the tree must be clean and rectangular.   By default, the line style must be the same throughout the tree (prior to any user customization).

**Comment by abusalehmdtayeen** [comment]
@arlin,  I made some modifications to solve this issue. Can you check in the development instance of the portal? Does it look  good?

**Comment by arlin** [comment]
Thanks, I'm going to close this.  

I am also going to make a prediction: this will cause problems in the future.  I can see that the tip branches have two segments.  Later on, when we offer the user more customizations, we will have to make sure that this branch is treated as one element, even though it is composed of two elements.   In fact, I can already see a problem.  Open a tree and select "line highlight".  This is what happens: 

![11](https://cloud.githubusercontent.com/assets/1659198/19539645/7f01aed4-9628-11e6-8c55-21bfbb13c6ca.png)

**Comment by arlin** [comment]
And this (blue node disk is the junction between the two segments)
<img width="415" alt="screen shot 2016-10-19 at 6 20 41 pm" src="https://cloud.githubusercontent.com/assets/1659198/19539711/e09907fa-9628-11e6-9a2f-c9c28cac5582.png">

**Comment by abusalehmdtayeen** [comment]
@arlin, I think I can solve this problem by making the color of the second segment same as the line highlight color.
