### ISSUE TITLE
redesign tree viewer control strip

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#227]
This ticket is unfinished.  Re-organize the viewer control strip to achieve greater clarity.  
1.  Change "Line width"  to "Line weight"
2.  Change "Node labels" to "iNode Labels"
3.  Add float-over to iNode Labels: "Show taxon names associated with internal nodes"
4.  Use graphical style (e.g., collect all items in a box) to show what the "Apply" button refers to.  Sometimes the user does not understand that they must press "Apply" in order to apply changes.  
5.  Change the spacing so that it looks nice. 
6.  Find a better way to describe the image download functions.  Don't say "download" if the image is not actually downloaded.

**Comment by hdliv** [comment]
1. Implemented
2. Implemented
6. now *load all images*

**Comment by hdliv** [comment]
closing
