### ISSUE TITLE
notification in desktop

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#23]
When names are extracted from a tree or a tree is constructed, there will show up a small notification box.

**Comment by arlin** [comment]
The notification boxes work!  

However, there are some anomalies and annoyances.  First the title of the notification box is always "Tree #<id> is ready", even if this notification is for name extraction.  

Also, if there are incomplete jobs.  The notifications re-appear each time the user logs in again or returns to the trees view.
