### ISSUE TITLE
List view load error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#236]
In anonymous mode, create an empty list by choosing "Extract from web" and providing a URL with no species names (e.g., www.phylotastic.org). 

The "Make a new list" menu does not load.  This is an important error because the next step for the user is to try again to create a list, but the options are not available.

**Comment by ducvan0212** [comment]
I tried to reproduce the error but I saw

<img width="1195" alt="screen shot 2016-10-19 at 1 03 41 pm" src="https://cloud.githubusercontent.com/assets/1614884/19533354/a136dfdc-95fc-11e6-9d0c-783cb06e9fa6.png">

**Comment by arlin** [comment]
I'm sorry, I made a slight mistake.  You are getting this error because you entered "www.phylotastic.org" instead of "http://www.phylotastic.org".  The portal does not recognize the first one as a URL (that's a separate issue) and returns an error immediately.  If you enter a valid URL, then you will be directed to list view and you will see the green banner indicating that the list is being processed.

**Comment by ducvan0212** [comment]
Ah, it is because last weekend, I performed a code refactor and I forgot to add the creation navbar in the new error layout. I added it back. Thank you Dr Arlin for discovering this.

**Comment by ducvan0212** [comment]
Can you check again? It is weird because I remember I did include "New list" and "List actions" in that layout. I just pushed things to the dev server

**Comment by arlin** [comment]
It works now.  thanks.  closing
