### ISSUE TITLE
highlight feedback tab when selected

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#241]
Highlight label of active tab.  This works for "Help" (image) but not for "Feedback" (image). The "Feedback" text seems to be bold, but the tab isn't shaded. 

![screen shot 2016-10-20 at 3 40 05 pm](https://cloud.githubusercontent.com/assets/1659198/19578287/109eb088-96e9-11e6-898f-8bfec0b55a65.png)

![screen shot 2016-10-20 at 3 39 55 pm](https://cloud.githubusercontent.com/assets/1659198/19578290/13492124-96e9-11e6-8917-dc1a255cef13.png)

**Comment by ducvan0212** [comment]
I forgot to highlight "Feedback" tab. I fixed this, Dr. Arlin.

**Comment by arlin** [comment]
When you fix something, move it to review, please.

**Comment by ducvan0212** [comment]
Because from my view, I did not see the review column so sometimes, after I add label to the ticket, it appeared in wrong column. Would you mind to check this ticket again? Thank you, Dr. @arlin.
