### ISSUE TITLE
fix confusing routing

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#244]
Choose "Extract from web".  This typically takes 3 to 7 seconds.  The green progress banner fades away after only a few seconds, and then "Welcome" message & graphic reappears, and then the new list is loaded.    

This is confusing.  Users think that their list has not been processed.  Here is how to fix. 

1.  display the green banner until the new list loads
2.  change the text in the green banner: <b>Extracting list</b>.  When finished, the new list will appear in the list viewer and will be available in <i>My lists</i>
3.  don't show the welcome message & graphic after the user clicks "Get names".  

The ideal solution would be to put a spinner in the list view area with a message.  This will focus the user's eyes correctly on the place where the list will be.  

I will make a mockup.

**Comment by ducvan0212** [comment]
I made this change, Dr. Arlin.

**Comment by arlin** [comment]
yes, this is much better!
