### ISSUE TITLE
activate "Get tree" when user hits return button

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#246]
From the list view, choose "Get tree".  Enter a name in the box and press return.  Nothing happens.  

Users expect that, when a dialog box requests text input, hitting the "return" button will close the dialog box and move ahead in the workflow. 

Please fix this by activating Get tree when the user hits the "return" key.

**Comment by ducvan0212** [comment]
I made this change, Dr. Arlin.

**Comment by arlin** [comment]
This does not work for me on dev.  I tested in Firefox, Chrome and Safari.

**Comment by ducvan0212** [comment]
I made a typo that prevents the javascript code executes. I fixed my typo. Would you please check again? Thank you, Dr. Arlin

**Comment by arlin** [comment]
OK, good.  Thanks.
