### ISSUE TITLE
Darwin Core file not uploading in :3001

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#250]
We are not able to upload a Darwin Core Archive in the development server.  

This is a test use-case: phylotastic-portal/interactive_test/Extract_from_DCA/Archive.zip

**Comment by ducvan0212** [comment]
I checked and see this 

=> {"status_code"=>204, "message"=>"List with ID 39 is not public. user_id must be list owner to access the list"}

Maybe there are some conflicts in list species development service. Can @abusalehmdtayeen take a look about this?

**Comment by arlin** [comment]
we have seen some problems that *look like* the portal is getting confused about ids for list.  @hdliv uploaded a list and the list view was showing the metadata for a different list.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , in my database the list with ID 39 is set as private. That means only the owner of the list can see the list, modify it or remove it. That is why you get that message. I don't see any conflict. Can you describe more about the scenario?

**Comment by ducvan0212** [comment]
I guess Dail submitted a DwC-A, the portal submitted the list to species list service. The list is public as it saved in the portal database but in species list service, it is marked as private list.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , I just checked this case by inserting a list through the list service API. It works. To make a list public, your service request must have a valid boolean value for the "is_list_public" property. Can you please check your end whether you are setting this property correctly when the user is trying to upload a list?

**Comment by ducvan0212** [comment]
@abusalehmdtayeen Can you check in species list service database to see if there are 2 records that have the same list_id 21?

**Comment by ducvan0212** [comment]
I saw in development database and see that some list_id returned from species service are duplicated. 

There is a record in development database for list_id 21 which is created at 10/24/2016:

=> #<UploadedList id: 7, created_at: "2016-10-24 17:01:39", public: true, status: true, lid: 21, reason: nil, name: "Marine vs Terrestrial Mammals Lesson", description: nil>

Then somehow, Dail could create another list with id 21 on 10/25/2016.

=> #<UploadedList id: 10, created_at: "2016-10-25 18:47:32", public: false, status: true, lid: 21, reason: nil, name: "Marine vs Terrestrial Mammals Lesson", description: nil>

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , I checked. There is only one record with list_id 21. Duplicate list_id is not possible. The list_id always increment whenever a new list is created. May be the the list information is the same if it is pushed two times to the species service by the same user. Since title of a list can not be used as unique, my only unique id is list_id.

**Comment by ducvan0212** [comment]
Can you check the content of list 21 in production species list service?

**Comment by hdliv** [comment]
I am able to upload now
