### ISSUE TITLE
welcome message missing on production

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#251]
The welcome message has disappeared on production.  This should appear in the center panel of List View (Home) whenever the user navigates back to Home.  I think it also should appear whenever the center panel would otherwise be empty.  For instance (and this may be the only instance), the center panel becomes empty when the user deletes the current list.

**Comment by arlin** [comment]
This is strange.  I checked Safari and I can see the welcome message.

**Comment by arlin** [comment]
Also, Firefox shows the welcome message.   Is this because I just started a session?  Is the welcome message on a timer?

**Comment by ducvan0212** [comment]
After you created a tree, I saved a variable in cookie to indicate that the welcome message should not be displayed.

**Comment by ducvan0212** [comment]
@arlin In #244, you said 

don't show the welcome message & graphic after the user clicks "Get names".

So I guess in Chrome, you did created a tree but in Firefox, Safari, you have not created any tree.

**Comment by arlin** [comment]
There is no contradiction here, if that is what you are implying.   When the user initiates an action, the user watches the app for feedback to understand what is happening.  If the user presses "Get names" and the app goes back to the welcome message, this tells the user "I totally forgot what you asked me, can we start again?"  If the welcome message is cleared away and a spinner appears, this tells the user something is happening and it suggests that the new results are going to appear in the center panel.  This is called a transition.  See item 10 of good app design here: http://www.designforfounders.com/web-app-ux/ . 

But this doesn't mean we should never show the welcome message again.

**Comment by ducvan0212** [comment]
@arlin Thank you for clarifying this issue for me. The welcome message was brought back.

**Comment by arlin** [comment]
good, very good.  I think we are almost ready to release.
