### ISSUE TITLE
failure to download taxon match report

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#252]
choose a list, choose taxon match report, choose save as PDF (or csv)

The results is an error "We're sorry but something went wrong". The error is the same for PDF or csv. 

Fix taxon report download functionality.

**Comment by ducvan0212** [comment]
@arlin I fixed this issue

**Comment by arlin** [comment]
OK, download works, but I noticed a problem with the csv formatting.  I will post that as a separate issue.  

I like seeing the phylotastic logo into the PDF!  it looks good.
