### ISSUE TITLE
empty "My trees" list with no clue for user

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#253]
When user has no trees, the "My trees" pulldown reveals an empty box.  It would be more helpful if this box were to say something like "You don't have any trees yet" or "Your trees will appear in this list".  

* new list: re-order items 1 Web, 2 Doc, 3 list, 4 taxon.

**Comment by ducvan0212** [comment]
@arlin I provided a text in the empty box when users do not have any tree.

**Comment by arlin** [comment]
good, thanks
