### ISSUE TITLE
Re-order New List menu items

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#254]
We want to put the easiest, most accessible options first, and the expert stuff last.  

Re-order the "Make a new list menu" as follows: 
1. web
1. doc
1. list
1. taxon

**Comment by arlin** [comment]
I don't see any changes on this @ducvan0212.    Be sure to push to dev if you want us to test things.

**Comment by ducvan0212** [comment]
I pushed this change to the server.  Would you mind to check it again?

**Comment by arlin** [comment]
Yes, good.
