### ISSUE TITLE
pulldowns do not close as expected

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#255]
Select item from Public Trees, My trees pulldowns.  The pulldowns do not close as expected (OSX, Chrome).  

Close pulldown when user selects an item.

**Comment by ducvan0212** [comment]
@arlin I made the dropdown closed right after user select a tree.

**Comment by arlin** [comment]
@ducvan0212 , I can't test this until #214 is fixed, because there is no way to put anything into public trees, apparently.

**Comment by ducvan0212** [comment]
After creating a tree, you can publish it by opening 'Tree Settings' and tick on Public: true.
<img width="334" alt="screen shot 2016-10-26 at 10 11 41 am" src="https://cloud.githubusercontent.com/assets/1614884/19734405/a4a5c7f6-9b64-11e6-8e26-c9ee7f3f723a.png">

**Comment by arlin** [comment]
I'm not seeing that.  I think you might need to push it to dev.

**Comment by arlin** [comment]
However, someone added a public tree named "Fox" and I verified that the pull-down is working as expected.  So this is closed.

**Comment by ducvan0212** [comment]
@arlin You can only see the "Tree settings" button when you are the owner of the tree. Would you please create a new tree and see that whether the button is in tree viewer?
