### ISSUE TITLE
internal FAQ link behavior

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#258]
The User guide on the Help page has an internal link to the FAQ item about species names.  The expected behavior would be that clicking on the link opens the accordion item on species names, and moves the focus to that item.  Currently the focus is moved but the accordion does not open.  

Either rewrite the text to remove the link (just "see the FAQ item . . . " instead of a link), or fix the link so that it opens the accordion.

**Comment by ducvan0212** [comment]
I write a piece of javascript so when you click on the link, the accordion will be opened.

**Comment by arlin** [comment]
Nice, thanks.
