### ISSUE TITLE
fail: copy action in tree export

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#259]
In tree view, click export, then copy.  The tree is not copied to the clipboard.  

Either remove this item (it isn't necessary as the tree can be selected and copied with the mouse), or make it work.  Removing redundant functions is always better.  Less is more.

**Comment by ducvan0212** [comment]
I removed the copy part from the code, Dr. Arlin

**Comment by arlin** [comment]
thanks.  closing.
