### ISSUE TITLE
stray line above treeview controller

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#260]
There is a horizontal line above the treeview controller panel.  Remove it.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen can you remove the this? This line is the pop up in ETE.

**Comment by ducvan0212** [comment]
We worked on this, Dr. @arlin

**Comment by hdliv** [comment]
i am closing this.  We are now having a redesign

**Comment by arlin** [comment]
why close this @hdliv?  Has the stray line disappeared?

**Comment by hdliv** [comment]
With the redesign, I dont think it is pertinent.  We will have to focus on issues then
