### ISSUE TITLE
fail: country pull-down in choose-from-taxon

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#262]
The country list pull-down has broken.  It is working on production, but not on dev.  

As seen in the picture, no default value is showing.  When I click on the pull-down to see the list, nothing happens (no viewable list). 

action: 
* fix so that the pull-down works as expected
* make the default "United States"

**Comment by ducvan0212** [comment]
@arlin After I reset the database in dev server, I forgot to re-insert the country list to the database. Now the country list is back on the dev server.

**Comment by arlin** [comment]
ok, good.
