### ISSUE TITLE
allowing list to be public

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#263]
The ability to make a list public is now under edit name.  This needs to be moved to the page where we upload the darwin core file, where the user can then choose if they want the list to public or not

**Comment by ducvan0212** [comment]
<img width="672" alt="screen shot 2016-10-26 at 12 52 57 pm" src="https://cloud.githubusercontent.com/assets/1614884/19740281/618aec8c-9b7b-11e6-9e65-b46a152afef9.png">

I added a line in DwC-A form so if users want to publish their list, they have to tick on the checkbox.

**Comment by hdliv** [comment]
Wonderful.  tried it out and working :)  closing this ticket

**Comment by arlin** [comment]
Good.  In the future, we may want to clarify this ("Make this a public list" would be clearer than "Allow others to watch").
