### ISSUE TITLE
tree view failure on production

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#265]
Somehow the tree is not being displayed in Tree View.  The "Export as" menu item is not loading either.  This suggests a database or other problem, rather than a problem with the ETE plugin. In the past, when the plugin failed, we could still get the Newick tree from "Export as".  

<img width="919" alt="screen shot 2016-10-26 at 12 48 52 pm" src="https://cloud.githubusercontent.com/assets/1659198/19735773/f1d5d898-9b7a-11e6-9b6d-a8079b745b24.png">

**Comment by arlin** [comment]
@ducvan0212, I just found out that this is only for *anonymous* users.  For logged-in users, the tree is displayed. So, obviously this is something about sessions or permissions.

**Comment by ducvan0212** [comment]
The tree did not load because of my typo. I did realize that and fixed it but I only pushed the patch to dev server.

**Comment by arlin** [comment]
@ducvan0212 , why not just test your code?  This is standard practice in the programming world.
