### ISSUE TITLE
install rails, try web UI

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#27]
Following directions at https://gorails.com/setup/osx/10.9-mavericks

**Comment by arlin** [comment]
Significant hassle installing Ruby 2.2.3 on OSX 10.9.5.  It all has to do with where the OpenSSL library came from, and whether the headers get read.   Use 

 RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/local rbenv install 2.2.3

**Comment by epontell** [comment]
Does it install out of MacPorts?

**Comment by arlin** [comment]
Yeah, I must have used MacPorts at some point in the past.  That was exactly the issue.  However, it took me 45 minutes to figure out.

**Comment by arlin** [comment]
phylotastic-portal uses postgresql.  that took some time to install.  Had to install with homebrew then 
env ARCHFLAGS="-arch x86_64" gem install pg -v '0.17.1'

**Comment by arlin** [comment]
Success!  Running Van's web tool on my laptop!

**Comment by ducvan0212** [comment]
@arlin To run background jobs, you need to run "redis-server" command in a terminal and "bundle exec sidekiq" in another one.
