### ISSUE TITLE
List view: show common name if available

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#270]
Users would like to see common names.  Eventually we may be able to provide common names for all lists.  However, let's begin by making common names visible when they are provided in the "vernacularName" column of a public list. 

To do: 
* If the list has a non-empty "vernacularName" attribute, show this in List view

**Comment by hdliv** [comment]
This was an initial request from those interviewed and a request from JH and KM after they tested the portal this weekend.

**Comment by ducvan0212** [comment]
@arlin  @hdliv The `common name` column is now available in list view in dev server.

**Comment by hdliv** [comment]
great-- took a look

**Comment by arlin** [comment]
Thanks, good job @ducvan0212
