### ISSUE TITLE
Tree found but not returned

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#272]
After 4 mins, this list still did not return a tree, though it was processing.  Can we figure out why?

to replicate: use the list provided.
   * click Upload my list
      * I have a text file with one name per line
   * click Get tree

**Comment by hdliv** [comment]
[2972_tips.txt](https://github.com/phylotastic/phylotastic-portal/files/568914/2972_tips.txt)

**Comment by ducvan0212** [comment]
What is the name of the list you store in the dev server?

**Comment by hdliv** [comment]
I tried this on :3000 not :3001

**Comment by hdliv** [comment]
this was on :3000   test 3

**Comment by ducvan0212** [comment]
@hdliv 
- I checked and your tree is extracted and is available in database. What do you mean "this list still did not return a tree"? Can you give me more details?
- I submitted your test file and I got the tree but it could not be display because the tree visualization in production seems to be down. 

@abusalehmdtayeen can you turn it back on?

**Comment by hdliv** [comment]
I meant that it is not visible.

**Comment by hdliv** [comment]
the trees >4000 tips return this: An unhandled lowlevel error occurred. The application logs may have details.

**Comment by ducvan0212** [comment]
Can you give me the 4000 tip list?

**Comment by hdliv** [comment]
i made a new issue for this

**Comment by hdliv** [comment]
![screen shot 2016-11-03 at 08 28 42](https://cloud.githubusercontent.com/assets/6361361/19967018/ce8c6868-a1a4-11e6-9930-5580fb020ef7.png)

I meant htat this never went away after progress bar finished

**Comment by ducvan0212** [comment]
Have you tried it on dev? The tree visualization in production was turned off.

**Comment by hdliv** [comment]
![screen shot 2016-11-03 at 09 10 29](https://cloud.githubusercontent.com/assets/6361361/19967145/65c6affe-a1a5-11e6-9951-44f5b300a7d5.png)

**Comment by ducvan0212** [comment]
Because the tree content is too big. Wait a second. I made a config to increase parameter size for our server.

**Comment by hdliv** [comment]
now i get this: 
![screen shot 2016-11-03 at 09 13 11](https://cloud.githubusercontent.com/assets/6361361/19967223/c70b73b2-a1a5-11e6-95c9-cfb6625e68ef.png)

**Comment by ducvan0212** [comment]
I turned off to reconfig.

**Comment by ducvan0212** [comment]
This is what I received in my end. The tree is too large to be extracted.

`Timed out reading data from server`

**Comment by abusalehmdtayeen** [comment]
@hdliv , for the list with 2972 taxons, I checked that a newick tree is obtained from OpenTree, but the tree image generated by ETE is too large to view in a browser. The image size is about 6.4MB.

**Comment by hdliv** [comment]
great @abusalehmdtayeen now we know.  We just will need to make sure we limit the amount of taxa from the user

**Comment by hdliv** [comment]
closing the issue
