### ISSUE TITLE
list corruption in portal

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#277]
Two species names from a previous bird list--  Aix sponsa and Anas strepera-- are now shown in the Finding Nemo list.  They don't belong there.  

Find out how the list got corrupted, and fix that.

**Comment by ducvan0212** [comment]
I received this from list service. 

=> {"status_code"=>200,
 "message"=>"Success",
 "list"=>
  {"list_species"=>
    [{"family"=>"",
      "scientific_name"=>"Aix sponsa",
      "scientific_name_authorship"=>"",
      "class"=>nil,
      "vernacular_name"=>"Wood Duck",
      "phylum"=>"",
      "nomenclature_code"=>"ICZN",
      "order"=>"Anseriformes"},
     {"family"=>"",
      "scientific_name"=>"Anas strepera",
      "scientific_name_authorship"=>"",
      "class"=>nil,
      "vernacular_name"=>"Gadwall",
      "phylum"=>"",
      "nomenclature_code"=>"ICZN",
      "order"=>"Anseriformes"},
     {"family"=>"NA",
      "scientific_name"=>"Chelonia mydas",
      "scientific_name_authorship"=>"NA",
      "class"=>nil,
      "vernacular_name"=>"Green sea turtle (Crush)",
      "phylum"=>"Chordata",
      "nomenclature_code"=>"NA",
      "order"=>"NA"},
     {"family"=>"NA",
      "scientific_name"=>"Amphiprion ocellaris",
      "scientific_name_authorship"=>"NA",
      "class"=>nil,
      "vernacular_name"=>"Clownfish (Nemo)",
      "phylum"=>"Chordata",
      "nomenclature_code"=>"NA",
      "order"=>"NA"},
     {"family"=>"NA",
      "scientific_name"=>"Paracanthurus hepatus",
      "scientific_name_authorship"=>"NA",
      "class"=>nil,
      "vernacular_name"=>"Regal Tang (Dory)",
      "phylum"=>"Chordata",
      "nomenclature_code"=>"NA",
      "order"=>"NA"},
     {"family"=>"NA",
      "scientific_name"=>"Zanclus cornutus",
      "scientific_name_authorship"=>"NA",
      "class"=>nil,
      "vernacular_name"=>"Moorish Idol (Gill)",
      "phylum"=>"Chordata",

**Comment by arlin** [comment]
Those two species are not in the DwC-A file.  I will put the sources in a repo somewhere.  @hdliv and @abusalehmdtayeen, is it possible that someone used the web services API to change the contents of the listserver,  perhaps by accident?

**Comment by arlin** [comment]
Also, I just uploaded another list to *production* (because dev was down) and THESE SAME TWO SPECIES appeared in my new list, even though they weren't in the file.  Because this happened immediately with a list that was not present before, we know that this is not due to an accidental edit by someone using the web service interface to the list server.  Instead, either the list server or the portal is somehow mixing.  Furthermore, when I uploaded the same list as a text file instead of DwC-A, I did not get the error.  

I will try to repeat this to see if it is an indexing error.

**Comment by ducvan0212** [comment]
I found the problem. After user submitted .zip file, this file is stored in the server. But the location used to store the file is not clean because the database reset command did not fully delete files in file location. This makes background job processes both old and new files. 

Next time, if I have to do a database reset, I should delete file location folder manually.
