### ISSUE TITLE
portal logs out users too aggressively

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#279]
I'm constantly getting logged out of the portal.  It seems that if I just change tabs and come back, I have to log in again.  The user should stay logged in for at least an hour unless they actually close the window.

**Comment by ducvan0212** [comment]
@arlin I use 2 different google applications for production and dev portal so if you sign in production then open dev in new tab, the cookie in dev which is for anonymous user overrides cookie in production. 

I dont think a credential shared between both dev and production is a good idea so please open dev and production in different browsers if you want to interact with both of them at a time. I signed in dev and open a new tab for dev, it still keeps my log in session in both tabs.

**Comment by arlin** [comment]
OK, I understand what is happening.  This issue will not affect most users because they will not be going back and forth between production and dev.  I will assign this to wontfix
