### ISSUE TITLE
match name fails due to trailing whitespace

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#288]
If a taxon name has a space after it, the search will fail.  

Strip out whitespace from before and after, before searching on a name.  

Optionally, suggest to OpenTree that they should do clean their inputs in the same way.

**Comment by ducvan0212** [comment]
Can you check again using your input file which you had trouble with before? I fixed this in dev server and checked by my own file. I want to make sure your case is also resolved.

**Comment by arlin** [comment]
Thanks.   Yes, I confirm that this works.   Moving this to "done".
