### ISSUE TITLE
italicize binomials

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#289]
The convention in scientific writing is to italicize binomials, i.e., _Genus species_.  Families may also be italicized.  Higher taxa usually are not italicized.  

Italicize binomials in the List view and the Tree view.  

If this is difficult to do without italicizing ALL taxon names, then just italicize ALL taxon names.  Mistakenly italicizing names of orders or classes  is a very minor issue.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen can we italicize species names in tree image?

**Comment by ducvan0212** [comment]
@arlin taxon names in list viewer is italicized.
