### ISSUE TITLE
Upon failure, provide user plain-language notification with instructions

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#297]
A major project goal for Q1 is to improve run-time reliability and robustness of the portal.

To achieve this goal, report back to the user on the point of failure.  This depends on #296.  

Also, provide the user with instructions.  The instructions may be simply "try again later", or something more detailed where appropriate.

**Comment by ducvan0212** [comment]
I added message like 

<img width="647" alt="screen shot 2018-06-03 at 9 16 11 am" src="https://user-images.githubusercontent.com/1614884/40888043-cf3ea1aa-670e-11e8-863a-d42b0e7817d1.png">

Depend on the feedback, I will improve the detail in the message in each part of the portal.
