### ISSUE TITLE
irregular behavior of accordion links in Help

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#300]
Go to Help in Chrome or Safari, click on the link in the top section to searching on common names, which goes to the anchor `#commonnames`.  Note the behavior.  Now, press the reload button.  

Try the same thing with the link to `#betterPlace` in "I got a tree, but ...". 

If I navigate directly to http://phylo.cs.nmsu.edu:3000/static_pages/help#commonnames, this does two things, it opens the accordion item, and it scrolls down so that the item is in view.  However, if I am already on the page and click a link to one of these internal anchors, I see the focus change but the accordion item does not open.  

This is not an important issue.  It is only an annoyance.  Possibly the best approach is just to take out the links.

**Comment by ducvan0212** [comment]
I fixed this issue. Now, whenever you click on an anchor, the screen will be scrolled to the anchor and the collapsed area will expand. You can check this behavior at the portal dev server http://phylo.cs.nmsu.edu:3001/static_pages/help
