### ISSUE TITLE
select binomials from scraped names

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#301]
When names are scraped from a source such as a web site or a PDF, it often includes a mixture of species designated by binomials (Genus species) and names for higher taxa.  In many cases, only the binomials are desired.  When there are more than a few dozen names, selecting them becomes tedious.  

Solution: in the List viewer, implement a button labeled "Species" for binomials, and another labeled "Higher taxa."  The user will be able to unselect all names, then select the binomials by clicking on the "Species" button.

**Comment by ducvan0212** [comment]
@arlin I wonder how the portal should discriminate binominals and names for higher taxa. Do binominals always have white spaces between string of characters while higher taxa don't?

**Comment by arlin** [comment]
@dimus, will you comment on this?  The simplest approach is just to assume that <word> is a higher taxon and <word><space><word> is a species binomial.  This will work most of the time, e.g., the "ant subfamilies" wikipedia page.  

The exceptions to this rule that might be important for phylotastic are
* species names sometimes have > 2 words because they refer to a subspecies or an authority
* common names for higher taxa may have > 1 word, e.g., "toothed whales" (Odontoceti)
* common names for species may have 1, 2 or more words e.g., "shag",  "European shag", "Little Black Cormorant" 

But I think we can ignore these until later.

**Comment by ducvan0212** [comment]
I can use Regex for filtering out names that have white spaces. When using Regex, we don't need to take care the number of words in names.

**Comment by ducvan0212** [comment]
@arlin the selector for displaying names or higher taxa is available in dev server.

**Comment by arlin** [comment]
Thanks, this is a good start. Can we give the user more choices by not hiding the unselected names?  For instance, when I scrape names from documents, I might want to begin by selecting all the species, and then add a higher taxon if there is no species to represent it.

**Comment by ducvan0212** [comment]
After getting the name list from the document, you can still do so by following these steps:
- Choose to display "species only"
- Choose to display "all". This will display all names but only species names are selected. 
- Run through unselected names and select the one you want to include in getting tree phase.

Note that the toggle select/unselect for all names will work for names that are being displayed only.

**Comment by arlin** [comment]
Thanks, that will allow me to accomplish my task.  However, from the perspective of designing the user experience this behavior will not be apparent to the  user.  Here is what the menu items actually do
* "all" - show all, do not change selection status
* "species only" - show only species AND deselect all groups
* "higher taxa only" - show only groups AND deselect all species

Two of the operations do two things at the same time, but we can't see the effect of both operations because hiding makes the effect of unselecting invisible.  This  behavior will be confusing to the user.  A user who thinks that the portal is only hiding but not unselecting might (1) choose species only, (2) select all species S1 to S10 with the select-all checkbox, then (3) choose "higher taxa" to add groups G1 and G6.  This would have the side-effect of unselecting S1 to S10, but the user would not see that.  If the user goes back to (4) selecting "species only" to check that S1 to S10 are selected, they will all be selected, but meanwhile, G1 and G6 will be unselected.   So then the user assumes that the list has G1, G6, and S1 to S10, but in fact the list only has G1 and G6 after step 3, and it has only S1 to S10 after step 4.

**Comment by ducvan0212** [comment]
@arlin I replaced the checkbox for toggle between select/deselect all names with a selection box with 4 options for displaying: all, species only, higher-taxa only and none. I hope this change is more user-friendly and still meets your requirements.

**Comment by dimus** [comment]
GNRD finds only "canonical forms" of names, however for botanical names it also picks up infraspecific epithets from time to time. So I would say 99.5% of the time number of words would represent what the found name suppose to be (unless there was a name-finding problem). There is also https://parser.globalnames.org as a most powerful and more complex solution.

**Comment by arlin** [comment]
@ducvan0212, thanks, this is going to be very useful!  Closing.
