### ISSUE TITLE
implement scaling methods in portal

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#306]
- [x] decide on data model relating scaled and unscaled trees.
- [x] design dialog box 
- [x] implement send list to scaling service 
- [x] implement show return tree
- [ ] implement trap null tree
- [ ] implement add metadata stanza 

See #304 and #305 for information on methods.

The action should be called "Add time scale".

**Comment by arlin** [comment]
Dialog box: 
"Assign branch-lengths proportional to time in MY (millions of years), using one of these methods: 
 * <b>Median</b>:  DateLife's median summary method (very fast)
* <b>OpenTree</b>: Extract from a dated version of the Open Tree of Life (fast)
* <b>SDM</b>: DateLife's Supertree Distance Matrix method (slow, not practical for > 10 tips).
The resulting tree will replace the current tree."

**Comment by arlin** [comment]
We also need to decide what is the relationship of the scaled tree to the original tree.  The simplest approach is to consider scaling as an irreversible alteration to the original tree.  The scaled tree will replace the original unscaled tree.  If the tree is scaled a second time with a different method, the newly scaled tree will replace the previously scaled tree.  This is the simplest approach.  Alternatively, we could preserve multiple versions of the tree with different scalings.  Alternately, we could preserve a single topology with multiple scalings.

**Comment by bomeara** [comment]
A scaled tree may have a subset of taxa, though, depending on the algorithm

**Comment by arlin** [comment]
so that eliminates option 3 in my previous comment

**Comment by arlin** [comment]
![Screen Shot 2018-06-15 at 4.20.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f66b7191a37cf1102b4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a19041c95df442e14451a415366bee742431.png)

**Comment by arlin** [comment]
![Screen Shot 2018-06-15 at 4.21.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f66b7191a37cf1102a4f5d5b5ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a29841c95df442e14451a41a3161e7722431.png)

**Comment by arlin** [comment]
![Screen Shot 2018-06-15 at 4.05.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f66b7191a37cf1122e4f5d595ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a29841c95df442e14451a5123e6ae1772431.png)

**Comment by arlin** [comment]
@abusalehmdtayeen we will need your help with this.  Our initial goal is to include the "median" method from DateLife instead of SDM.  Can you create a version that invokes median instead of SDM?  All the other parameters are the same?

**Comment by arlin** [comment]
![Screen Shot 2018-06-15 at 4.31.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f66b7191a37cf1112a4f5b595ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a29841c95df442e14451a3113564ef722431.png)

**Comment by abusalehmdtayeen** [comment]
@arlin , Yes I will update the datelife service to do that.

**Comment by arlin** [comment]
I'm closing this and opening a different ticket, partly because we revised our design for this, and @ducvan0212 has implemented the redesign.
