### ISSUE TITLE
improve error message for retrieval failure

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#308]
Current message: 
> We could not extract the tree. Please leave us a message at feedback so we can investigate your case further.

I would like to encourage users to try again.  Replace message with

> Tree retrieval failed, possibly due to a temporary interruption in back-end services.  Please try again in an hour, and if that doesn't work, leave us feedback.   

![Screen Shot 2018-06-18 at 6.05.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fb6b7191a37ef1122e4f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a19141c95df442e2485ca215376ae6762431.png)

**Comment by ducvan0212** [comment]
The message is changed and is available at dev server
<img width="1161" alt="screen shot 2018-06-18 at 5 10 19 pm" src="https://user-images.githubusercontent.com/1614884/41566831-9175af86-731a-11e8-8bf0-bb0b9f887b6e.png">
