### ISSUE TITLE
bug in taxon sample by genome

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#309]
in dev
* choose sample from taxon
* enter "Felidae"
* choose "by genome" 

exception: 
> ActionController::InvalidAuthenticityToken in TaxonomiesController#create
> ActionController::InvalidAuthenticityToken
> Extracted source (around line #195):
> 193
> 194        def handle_unverified_request
> 195          raise ActionController::InvalidAuthenticityToken
> 196        end
> 197      end
> 198    end

**Comment by ducvan0212** [comment]
The token used in dev and production is saved at the same cookies since both dev and production are same domain.
The way to fix is separate dev and production in 2 different domains.

**Comment by arlin** [comment]
OK, closing this.
