### ISSUE TITLE
revise scaling interface

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#313]
- [x] count tips on unscaled tree
- [x] add "tips," e.g., "Unscaled tree (13 tips)"
- [x] instead of "undetermined", just use "(?)"
- [x] refresh view so that tip-count replaces "?" when the tree has been retrieved
- [x] redesign so user knows these are 4 alternatives
- [x] give the alternatives a name like "Tree version"

**Comment by arlin** [comment]
maybe like this
![Screen Shot 2018-06-19 at 12.59.06 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a379ed0c2e58415f48bc21254d58eeb9cb74fce36f34985619e8d4680d71c43a44ffecd34aee54bf768b4f81b4ef831ac5fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e84957ad153767e675316e0a.png)

**Comment by ducvan0212** [comment]
The new design can be seen in dev server

**Comment by ducvan0212** [comment]
I moved the revert button to second column and make it a clickable link.

**Comment by arlin** [comment]
Thanks.  This is much clearer.  Closing this.
