### ISSUE TITLE
tree persistence bug

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#315]
In the portal, create named list A and make trees A1, A2.  

Now delete list A.  

The tree menu still lists A1 and A2 but apparently they are not available.  Selecting A1 or A2 will result in an error message:

![Screen Shot 2018-06-20 at 3.57.57 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f36b7191a37bf1172c4f5a585ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a19041c95df442e44f50a4123067e7762431.png)

**Comment by ducvan0212** [comment]
I fixed this issue. I forgot to delete the trees associated with a list when upgrading the portal. 

From now on, If you delete a list, the trees associated with the list will also automatically be removed.

To deal with existing trees associated with a deleted list, you still see the tree from tree viewer dropdown but if you click on that tree, the tree will be removed.

Thank you @arlin for pointing this out.

**Comment by arlin** [comment]
OK, thanks.
