### ISSUE TITLE
spot-check of scaling accuracy

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#316]
The dev portal currently allows median-scaled trees from DateLife.  These are shown with a scalebar in millions of years.  We haven't tested yet whether these values are correct.   They might be mistaken if there are mistakes in the code. 

Pick a case such as felidae for which we know the dates expected from DateLife resources, and use this to test whether the dev portal is representing dates accurately for a median scaled tree.

Another way to test is to use TimeTree.  Download a list from the portal, upload it in TimeTree, which accepts the one-name-per-line format.

**Comment by arlin** [comment]
I'm checking this using the desert plants list.  Note that TimeTree cannot find about 12 of the species out of 15, so I can't use TimeTree to check this.

**Comment by arlin** [comment]
Cat family.  Start with Stephen J O'Brien paper in Sci. American.   http://www.bio-nica.info/biblioteca/O'brien2007EvolutionCats.pdf.

**Comment by arlin** [comment]
OK, I have now done a comparative analysis of scaling for Felidae.  The results are here: 

https://www.dropbox.com/sh/lx7xf0bdw1z88ah/AAC7hJoVjnDAGpskuxJ5S9Ica?dl=0

**Comment by LunaSare** [comment]
I finished trying both felidae and desert plants examples and some others from the lists available on phylotastic portal. 
median and sdm trees displayed on the portal come from using a tree as input. When using names as input, results are different. That's why my tests and the portal trees were different. Please see issue https://github.com/phylotastic/phylotastic-portal/issues/322

**Comment by arlin** [comment]
Our analysis of this yesterday and today is that the Felidae results are acceptable given that there is disagreement among the published chronograms, and disagreement among scientists.  We just need to do some things to notify the
