### ISSUE TITLE
auto-fade the new tree message

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#317]
When a tree is displayed, there is a message like the one below. To make the message disappear, the user must click the "X".  

The message will reappear if the user switches to a different version of the tree (scaled version) and then switches back.   This behavior makes the first behavior more annoying. 

To do: 
* Don't require the user to dismiss the notice.  Make it fade away automatically in 5 seconds.  The number of tips is still visible in the tree-version chooser. 
* Dismiss the notice permanently. Don't re-display it when the tree version is selected again.   

![Screen Shot 2018-06-23 at 2.17.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/555b5266657c0c8300c2bee1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f06b7191a37af1132c4f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee8d43f5a76c16842f8e9d74eea04ec208b4b87e5b5dc49d2f42f67b6d5db1063474f4dcbed5727a19141c95df442e64a5ca6163164ee752431.png)

**Comment by ducvan0212** [comment]
Yes, I did. Closed this issue.
