### ISSUE TITLE
shorten text on load images button

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#321]
Current text 1: Approximate time for downloading of all images is `<time>`s.  Please wait until notified of completion of download. 

New text 1: Wait  ~`<time>` seconds for image retrieval, then re-click. 

Current text 2: Download complete.  Please click the load images button again. 

New text 2: Done.  Click again to display images on tree.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , Thanks for reminding me. I will do the modification.

**Comment by abusalehmdtayeen** [comment]
Done for ETE dev service.
