### ISSUE TITLE
try to understand stress test result

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#328]
@LunaSare finds “RuntimeError in TaxonController#show”.  

1. Try to reproduce this error.  
2. Note the results of #1 in the google doc
3. If reproducible, make a ticket to fix this.

**Comment by arlin** [comment]
So, how can I test that?

**Comment by ducvan0212** [comment]
You can follow what Luna described in the load test report

**Comment by arlin** [comment]
Could you please be more specific?  Do you mean to choose the extract-from-web workflow with https://es.wikipedia.org/wiki/Primates?

**Comment by ducvan0212** [comment]
Yes, I guess so. Luna did not provide the wiki link in the load test report so I also used your provided link. Then you extract the matching report in pdf format.

**Comment by arlin** [comment]
OK, it works, issue resolved. Thanks.
