### ISSUE TITLE
generate list from doc default method

### ISSUE THREAD

**Issue by LunaSare** [phylotastic/phylotastic-portal#336]
Default **method** should be NetiNeti & TaxonFinder
Current Default is NetiNeti, but it could not generate a list from an excel table with flowering plants family names.
A list is generated when using method TaxonFinder.
[_species richnness angios families susana apw 2014.xlsx](https://github.com/phylotastic/phylotastic-portal/files/2336688/_species.richnness.angios.families.susana.apw.2014.xlsx)

I would also add an information icon on what NetiNeti and TaxonFinder tools are.

**Comment by ducvan0212** [comment]
I updated the default method in extracting names from doc to NetiNeti and TaxonFinder
