### ISSUE TITLE
build tree from pre-compiled lists view

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#34]

**Comment by hdliv** [comment]
@ducvan0212   do you have the lists, or should i send you others?

**Comment by arlin** [comment]
@hdliv, the lists are going to come from the list server, which has the lists you sent to @abusalehmdtayeen .  If you have some good examples, add them to the list server.  We will want the web tool to provide the user with a set of interesting lists for making trees.

**Comment by hdliv** [comment]
I guess my question is then @abusalehmdtayeen  Do you want more lists?  I can send more.

**Comment by arlin** [comment]
my question is @hdliv, do you have an awesome list that would really improve the user's experience with the web tool?  Right now, this is the sole purpose of the list server.

**Comment by hdliv** [comment]
we have spoken a bit about birds because of enthusiasts, and we do not have a bird list @arlin

**Comment by abusalehmdtayeen** [comment]
@hdliv , If you have more lists, you can send it to Van. He will integrate my species list services with the web portal. So he will need some files to test the import process. I would also suggest you to keep some files with you. When Van finishes the integration, you can test import those as a user.

**Comment by ducvan0212** [comment]
This feature is available on the server. I just test it in my local machine.

**Comment by arlin** [comment]
@ducvan0212, please provide us more information so that we can try this.  We want to provide the user with specific examples, e.g., birds of Maryland.  I do not see any lists.   Here is what I see when logged in to the portal
<img width="823" alt="screen shot 2016-04-05 at 9 27 14 am" src="https://cloud.githubusercontent.com/assets/1659198/14283592/effd0262-fb11-11e5-904a-f3d413c48680.png">

**Comment by ducvan0212** [comment]
To create a list of species, you have to submit your file compression on the right form. 
- If you want others also use your list, check the opt "Allow others to watch this list". If submitted successfully, your list will available in both "From your own list" and "From our database" sections.
- If you kept your list privately, your list will not be public and it will be only available under "From your own list"

After that, you are able to create trees from submitted list or edit species in that list from "Jobs" view

**Comment by ducvan0212** [comment]
I just created a public list. Can you see it under "From our database"?

**Comment by arlin** [comment]
Yes, I can see it. Thanks.  Have you tried to make a tree from it?  I get an error.

**Comment by arlin** [comment]
ActionController::UrlGenerationError in Trees#index
Showing /home/van/phylotastic-portal/app/views/trees/_prebuilt_list_content.html.erb where line #29 raised:

No route matches {:action=>"show", :controller=>"uploaded_lists", :id=>nil} missing required keys: [:id]
Extracted source (around line #29):
27
28
29
30
31
32
              
            
          <% when 2 %>
            <%= link_to "View species of list", uploaded_list_path(id: j["list_id"]), class: "btn btn-primary" %>
            <%= form_for(current_user.user_list_relationships.find_by(uploaded_list_id: ul.id), html: { method: :delete }) do |f| %>
              <%= f.submit "Remove", class: "btn btn-danger", style: "margin-top: 5px;", data: { confirm: "Removing a job will also delete all trees belonging to that job. Are you sure?" } %>
            <% end %>

Trace of template inclusion: app/views/trees/index.html.erb

Rails.root: /home/van/phylotastic-portal

Application Trace | Framework Trace | Full Trace
app/views/trees/_prebuilt_list_content.html.erb:29:in `block in _app_views_trees__prebuilt_list_content_html_erb___758120236679239301_70133688449320'
app/views/trees/_prebuilt_list_content.html.erb:1:in `_app_views_trees__prebuilt_list_content_html_erb___758120236679239301_70133688449320'
app/views/trees/index.html.erb:53:in `_app_views_trees_index_html_erb__3484636680264363912_70133595106820'
Request

Parameters:

None

**Comment by arlin** [comment]
BTW, if this is a date problem then it is probably due to an Excel conversion of 4/5/2016 to "5-Apr-16". I have fixed this and tried again, but I'm still getting database errors that are completely unrelated.

**Comment by arlin** [comment]
@ducvan0212, I'm going to be working on other projects for the rest of the day.  I'll get back to this tomorrow however.  Good luck.

**Comment by ducvan0212** [comment]
I found the error. It is because of incompatibility between database in my local machine and database in server. For example, your user id is 1 in server but in my machine, I am the user who has id 1. We have only one service for development, test and production so these data are not synchronize. I am fixing this error by manually modify records in service of Abu. Hope it will work back soon. Sorry about this.

**Comment by arlin** [comment]
ok, we should close #57 on this basis, and write another ticket to (1) set up a test server that is separate from Van's development server and (2) configure the test environment so that this problem does not happen.  @ducvan0212 , could you do that please?

**Comment by ducvan0212** [comment]
I create #59 to ask @abusalehmdtayeen  to create a development service. 
I did a hot fix so as I tested, the server works on prebuilt-list case but in my local machine, I got the "expected" error.

**Comment by arlin** [comment]
@ducvan0212 ,  I think this feature has been implemented.  Could you please move this to Review?
