### ISSUE TITLE
error in common names extraction for a tree

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#342]
=> "{\"newick_tree\":\"((((((Tipularia discolor)Tipularia)Calypsoinae)Epidendreae)mrcaott334ott908,(((((Spiranthes infernalis)Spiranthes)Spiranthinae,((Ponthieva racemosa)Ponthieva)Cranichidinae)Cranichideae,(((Platanthera praeclara)Platanthera)Orchidinae)Orchideae)Orchidoideae)mrcaott335ott27841)mrcaott334ott335,(((Vanilla inodora)Vanilla)Vanilleae)Vanilloideae)Orchidaceae;\"}"

=> "{\"message\": \"Error: local variable 'tip_mapping' referenced before assignment\”}"

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , I have fixed this.
