### ISSUE TITLE
Get a TLS cert so people can connect via https

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylotastic-portal#343]
Various browsers now scare users when going to an http site.

**Comment by ducvan0212** [comment]
@arlin @bomeara @dimus Can we purchase a SSL certificate? The cheapest certificate I find from https://www.digicert.com/order/order-1.php is about $200. Is there any cheaper options?

If we use a self-signed certificate, it is free, but the browser will still display a warning to scare users.

**Comment by arlin** [comment]
yes, it seems that we should get a certificate.  ask @epontell since you guys are going to be the ones using it.
