### ISSUE TITLE
minor improvements to text entry

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#351]
- [x] on the main list menu, change menu item label to "Enter my list"
- [x] on the main list menu, make this item 3, before "Upload my list" 
- [x] on the text input view, change page title to "Enter list manually"
- [x] on the text input view, add explanation after title, before box: "Enter a list of names into the text box below.  For best results, add a separator such as a comma or semi-colon after each name."
- [x] on the text input view, change the grayed-out text in the buffer to "e.g., Canis lupus, Panthera pardus, Melursus ursinus, Macaca mulatta"

**Comment by ducvan0212** [comment]
I made the changes and they are all available in production server.

**Comment by arlin** [comment]
thanks!
