### ISSUE TITLE
feature request: bibtex (or other) export 

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#354]
Go to google scholar profile page, select a few references, you get a pull-down menu with options to export.  We would like to have something like this for the metadata page. 

Favorite options for scientists are bib and RIS.  RIS is an old format but it is still the portability standard for users of EndNote and RefMan.  

Ask @arlin or @bomeara if you have questions about this.

**Comment by ducvan0212** [comment]
For now I can only find a conversion from DOI to bib. I didn't find any web services to convert from DOI to RIS.
