### ISSUE TITLE
fix bibliography UI and export option

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#356]
the portal now has a highly useful bibliography feature, with links to OT viewer, original paper, and option to download.  

- [x] check that the bibtex output is correct, e.g., use a [bib checker](https://biblatex-linter.herokuapp.com/).  Also, note that some bibtex parsers expect spaces around the "=".  Please add the spaces around "=" and the carriage returns.  
- [x] put "check (uncheck) all" next to the checkbox at the top left
- [x] move the "Show selected citations" text to top-right, make it a button, and label it "Export citations (BibTeX)" (if we have other options, label it "Export citations")
- [x] optionally, add float-over for Export button "Generate BibTeX entries for these studies in a pop-up" 
- [x] change "Read paper" to "Find this paper (via DOI)"
- [x] change "View OT" to "View tree at OpenTree"

Also, I would suggest to change the "Save" button next to the metadata as follows: 
- [x] change label from "Save" to "Save metadata (JSON)"
- [x] add a floatover:K "Save metadata with study IDs. For bibliographic sources, use the Export feature".

**Comment by ducvan0212** [comment]
Can you check if you can import the bibtex generated by the portal?

**Comment by arlin** [comment]
The function activated by the export function does not seem to be getting up-to-date or accurate information about the number of entries selected using the checkboxes.  Sometimes I get stuck on this error message even when all the boxes are checked. 
<img width="688" alt="Screen Shot 2019-10-04 at 9 37 34 AM" src="https://user-images.githubusercontent.com/1659198/66211802-bc449f80-e68a-11e9-8625-254a948d43f9.png">

**Comment by ducvan0212** [comment]
@arlin It is not updated because the bibtex is generating in the server. I added the loading icon, so it looks good now.

**Comment by arlin** [comment]
When I select "Export" with all the check-boxes checked, I see the spinner (image) for several minutes, with no results.  When I select just 2 entries, I can get the bibtex, but it does not parse.  I don't know why it doesn't parse.  

<img width="688" alt="Screen Shot 2019-10-04 at 1 41 52 PM" src="https://user-images.githubusercontent.com/1659198/66228817-697cdf00-e6ae-11e9-9fda-49033b196dbd.png">

**Comment by ducvan0212** [comment]
@arlin Can you try to get all the study entries? I just fix the error that causes the frozen in studies querying process. Basically, a url to a study is not DOI so the portal couldn't resolve it into bib.

I also tried to parse the downloaded bib file in bib checker, and the file is parsable. I also included the bibfile in latex, and it perfectly works.

**Comment by arlin** [comment]
OK, everything works now.  Closing this.  The slowness is because we get bib entries from OT, extract the DOI, then get a bibtex for the DOI?

**Comment by ducvan0212** [comment]
I believe @abusalehmdtayeen set 1 second between each call to OT service for the studies. Before, it didn't take that long to extract all studies of a tree.
