### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#36]
I ignored this file because config.yml contains url to web services. These endpoints should not be exposed to outside world. The content of config/config.yml is pasted following

development:
  sv_findnames:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/fn/names_url?url="
    method: "get"
  sv_resolvenames:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/tnrs/ot/names"
    method: "post"
  sv_gettree:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/gt/ot/tree"
    method: "post"
  sv_speciesfromtaxon:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon="
    method: "get"
  domain: "http://0.0.0.0:3000"
  
test:
  sv_findnames:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/fn/names_url?url="
    method: "get"
  sv_resolvenames:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/tnrs/ot/names"
    method: "post"
  sv_gettree:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/gt/ot/tree"
    method: "post"
  sv_speciesfromtaxon:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon="
    method: "get"
  domain: "http://..."
  
production:
  sv_findnames:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/fn/names_url?url="
    method: "get"
  sv_resolvenames:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/tnrs/ot/names"
    method: "post"
  sv_gettree:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/gt/ot/tree"
    method: "post"
  sv_speciesfromtaxon:
    url: "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon="
    method: "get"
  domain: "http://..."

**Comment by arlin** [comment]
This works.  Thanks.

**Comment by arlin** [comment]
Other things are working now.  The database is no longer the problem.  So this is finished.
