### ISSUE TITLE
write test for faq page

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#4]

**Comment by arlin** [comment]
"write test" or "write text"?

**Comment by ducvan0212** [comment]
I will try to apply test-driven development for the web portal. Test should be written before model, view and controller are developed but we havenot choosen which test framework to be used. Cucumber, Travis and Capybara are under consideration.

**Comment by arlin** [comment]
OK, part of our (UMD) job in the project is to help out with the content of the tests.  We should start discussing that right away.

**Comment by hdliv** [comment]
We have added info to this page
