### ISSUE TITLE
improvements to "trees" (jobs) view

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#40]
Currently there is a view available at <server>/trees, which shows a table of the user's jobs.  I did not realize for a long time that this is accessible via the "Gallery" navbar item.  The conception of "gallery" in the design for the web UI was more of an image gallery.  To me this looks like a list of jobs.  I would call this view "Jobs" and try to design the system so that the user does not need to see this page, because ultimately we want this tool to deliver trees on-the-fly.  

Some of the ways to improve this would be 

#### Add a title and some explanation. I would suggest:

"Phylotastic jobs

All of your jobs are shown here, with the most recent ones on top.  The status column will tell you what is the status of your job, and what are the steps available." 

####  Make some changes to the table to clarify what is going on. 
* keep the Id column but don't link t.id to tree_path(t.id) (see Actions column below)
* make "Source" the second column (after Id)
* change "Source" to "Content of tree"
   * in table rows, change "URI: " to "Names extracted from URI: " 
   * in table rows, change "File: " to "Names extracted from File: "
* make "Status" the third column
* change the Status messages to direct the user
   * s/resolved/Names acquired: click "verify names" to approve list and get a tree/
   * s/unsucessfully-resolved/Sorry! We could not acquire a list of names!/
   * s/unsuccessfully-constructed/Sorry! We could not acquire a tree!/
   * s/completed/Tree acquired: click "View tree" to see it
* Put all of the actions in one column, and call it "Available actions" 
   * the first action is "Check status" 
   * the next action is edit_tree_path(t.id) which should be labeled "Check name list"
   * the next action is to view the tree.  This should be conditional on status, that is, if t.status == "completed" , <%= link_to "View tree", tree_path(t.id) %>, otherwise the user just gets an error.  
   
#### Make the alerts more informative. 
When names are acquired for job #11, the message says "Tree #11 is ready.  Come back to prune your tree!"  But the tree is not ready.  Change this to "Names have been acquired for job #11. To proceed, choose 'Check name list' in the Jobs table." 

![image](https://cloud.githubusercontent.com/assets/1659198/13441369/c088d2ee-dfc4-11e5-9a41-72e36582917e.png)

**Comment by ducvan0212** [comment]
Current view is just temporary and your suggestion is very helpful in re-designing the user interface of Job page. I appreciate that

**Comment by ducvan0212** [comment]
Currently, the gallery tab points to "listing of your trees" page. It will point to "listing of trees which  you like to follow" soon

**Comment by ducvan0212** [comment]
I made some changes as your recommendations. I think the user interface of this web page is still need to be improved

**Comment by arlin** [comment]
Yes, I think the "jobs" view is much better.  Is "delete" supposed to work?  I can't get it to work.

**Comment by arlin** [comment]
Yes, I can confirm that delete works.

**Comment by arlin** [comment]
I get the "View tree" and "Delete tree" options even when no tree has been acquired yet.

**Comment by ducvan0212** [comment]
Would you please provide me the tree id of this case? In my code, I allow "View tree" only when the tree is acquired.

**Comment by arlin** [comment]
@ducvan0212, I haven't been responding to this because it hasn't been a priority.  We want to delay any UI improvements until the 3 basic portal workflows are implemented.  Once the 3 workflows are implemented, @hdliv and I can test them.  When the workflows have passed basic tests, then we will be ready to start working on (1) adding features and (2) UI redesign.

**Comment by ducvan0212** [comment]
It is fine, professor.
