### ISSUE TITLE
remove ottIds from display names on trees

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#41]
Rather than showing "Grammostola_rosea_ott124289" at the tip of a tree, show "Grammostola rosea".

**Comment by ducvan0212** [comment]
I filtered only the name of species in tree viewer. Thanks you for notifying me about this

**Comment by arlin** [comment]
This is much cleaner!  But users will want the entire "binomial" name, with two parts.  For instance, for the eleven_plant_species example I should see "Agave americanus" instead of just "Agave", and so on.  The names we get from OT are <genus>_<species>_ottID<number>, and we want to display <genus> <species>.

**Comment by ducvan0212** [comment]
Every specie names looks good now.
