### ISSUE TITLE
returned string is not in JSON format

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#52]
https://drive.google.com/file/d/0B7SKJwE3SsCsUHdTOHl5TG9rTEE/view?usp=sharing

**Comment by ducvan0212** [comment]
https://drive.google.com/file/d/0B7SKJwE3SsCsUHdTOHl5TG9rTEE/view?usp=sharing

**Comment by ducvan0212** [comment]
@abusalehmdtayeen  Would you please give it a look?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , this has been fixed. Please check again.
