### ISSUE TITLE
add a species image to nodes of tree

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#56]

**Comment by arlin** [comment]
that sounds great! but I'm not seeing an images for my "Felidae" taxon tree.  Can you provide an example, please?

**Comment by ducvan0212** [comment]
When you hover your pointer(mouse) in nodes of tree, there will be shown a small information circle. Click on that and a image will be displayed. Click again to dismiss the image. It worked but for now, I can not get the images of species because Abu is still working on image service so I replace the images with a image stored in the server.

**Comment by arlin** [comment]
I have tested this yesterday morning and found that it works.  Thanks . We need to change the layout but this is good for now.  A very useful feature.
