### ISSUE TITLE
list processing error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#57]
1. Upload zip archive of species list
2. Notification says "Your list can not be imported" and jobs view says "Importing error! Please check again your file content." 

Note that, for purposes of testing, this is a list of 10 randomly chosen extinct species from PaleoDB.  We expect to find names in GNRD but we do not expect to get trees. 

If this is actually a bug in the list-processing web service, then please open a separate ticket for that in the appropriate web services repo.

[Extinct10.zip](https://github.com/phylotastic/phylotastic-portal/files/204712/Extinct10.zip)

**Comment by arlin** [comment]
BTW, @ducvan0212, I am assuming that the list is properly formatted, because it was composed by editing the example provided.   I have tried saving the files with Mac, Unix and Windoze line-endings, but nothing works.  @abusalehmdtayeen, can you check that the files are properly formatted?

**Comment by arlin** [comment]
I have verified that processing works for the case of using the template as an example.  I can download this, zip it on my mac, and upload the zip file to the portal.  The portal processes the example and produces  a visible species list.

**Comment by arlin** [comment]
I have noticed a separate issue whereby my unsuccessful lists are invisibly present in the jobs queue. I continue to get notifications but they do not appear in the jobs view.  I added this as a separate ticket (#58).

**Comment by abusalehmdtayeen** [comment]
@arlin: The file format seems correct to me. You can try by saving the file as Plain CSV or Windows Comma Separated (.csv) format. Because the end-of-line convention in a file are different under different systems (e.g., \n under Linux, \r under Mac and \r\n under Windows).  The client which is reading the CSV files should use universal mode for opening the files.

**Comment by abusalehmdtayeen** [comment]
@arlin; I forget to mention that the list file should contain valid date value for the list_date_published field.

**Comment by arlin** [comment]
Yes, that is the problem.  The file had "NA" for the date published field because this was a personal list, not something published.  When I replaced that with a date, it worked.  

However, this is not ideal.  I will write a separate ticket to rethink this.
