### ISSUE TITLE
jobs view error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#58]
I have tried numerous list uploads that have failed.  They do not show up in my jobs list.  However, I know that the jobs are still there, because the portal tries to re-process every input whenever the jobs view loads, and then it sends me notifications .  So I see many "Your list can not be imported" notifications even though the jobs are not visible in my jobs view.

**Comment by ducvan0212** [comment]
I took a look and it said that your date is invalid. Would you please provide your date written in your files?

**Comment by ducvan0212** [comment]
Can I see your files?

**Comment by arlin** [comment]
attached to #57

**Comment by arlin** [comment]
BTW, I think you are asking about #57 here, failure to process.  The fact that the jobs are not visible seems like a completely separate issue, which is why I created #58.
