### ISSUE TITLE
set up a test prebuilt-list service

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#59]
Data is not uniformed when requests which come from my local machine (test env) and the server (production env) will be saved on only a database.
Refer to #34

**Comment by abusalehmdtayeen** [comment]
Right now, the species list services already save data in only one database in the server. @ducvan0212 : I did not understand what you want me to do. Please explain more about this issue.

**Comment by arlin** [comment]
@abusalehmdtayeen, the context for this is that we are using Van's single-user development environment as a multi-user test environment.   When both Van and I are using the server, there are conflicts.

**Comment by ducvan0212** [comment]
This is solved by taking user identification as email
