### ISSUE TITLE
Genome NCBI use case

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#60]

**Comment by ducvan0212** [comment]
@abusalehmdtayeen Would you please give me more information and description of this use case so that I can start working on it.
I also tag Prof. @arlin so he can give his comments or modifications in case he wants.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212: Let me create the web service for this case first. Then I can write the description and you can integrate it with the portal.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , The use case for taxon to species having genome sequence is similar to taxon to all species. The user will give a taxon name as input and click on the option to get subset of species that have genome sequence in NCBI. My web service will return that for you. From that step you follow the usual work flow which is to resolve through Open Tree and get tree.  I have added the API description in web service 18 of https://github.com/phylotastic/phylo_services_docs/blob/master/ServiceDescription/PhyloServicesDescription.md

**Comment by ducvan0212** [comment]
Thank you, Abu.

But I wonder what if user select a subset of species that have genome in
NCBI and *found in the US for instance.*

I removed all the prebuilt list related things so you can take your time to
refine these services.

**Comment by ducvan0212** [comment]
By the way, would @abusalehmdtayeen please use status_code or statuscode uniformly over all services?

"{\"status_code\": 200, \"message\": \"Success\", \"species\": [\"Panthera tigris amoyensis\", \"Panthera tigris altaica\", \"Panthera tigris\"], \"taxon\": \"Panthera\"}"

=> "{\"message\": \"Success\", \"statuscode\": 200, \"taxon\": \"Panthera\", \"species\": [\"Panthera gombaszoegensis\", \"Panthera leo\", \"Panthera uncia\", \"Panthera pardus\", \"Panthera onca\", \"Panthera tigris\"]}"

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , now every service will provide status_code.

**Comment by arlin** [comment]
I get an error regardless of the taxon specified, e.g., "felidae", "mammalia".  this is the error: 

undefined method `[]' for nil:NilClass

Extracted source (around line #6):
4
5
6
7
8
9
              
  def create
    if params["subset_taxon"]["has_genome_in_ncbi"] == "1"
      response = Req.get(APP_CONFIG['sv_ncbi_genome']['url'] + params[:subset_taxon][:name])
    else
      response = Req.get(APP_CONFIG['sv_species_from_taxon']['url'] + params[:subset_taxon][:name])
    end

Rails.root: /home/van/phylotastic-portal

Application Trace | Framework Trace | Full Trace
app/controllers/subset_taxons_controller.rb:6:in `create'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"AgiZ21seq+MvFF6+Hg+3tudT1U067TgBs2Xlo3u6ZVYu2vdEFBdFh+1P2plwJQLTVWQYjafG+we1DIR4xokN7A==",
 "subset_taxon"=>{"name"=>"felidae",
 "description"=>"",
 "has_genome_in_ncbi"=>"1"},
 "commit"=>"Find subset of species"}

**Comment by ducvan0212** [comment]
I forgot to update the config. This is fixed, Dr. Arlin

**Comment by arlin** [comment]
Everything is broken now, but  I tested this last week and it worked.

**Comment by ducvan0212** [comment]
I tested and this feature worked. What is the error?

**Comment by arlin** [comment]
the portal was broken this morning. now its working again.

**Comment by ducvan0212** [comment]
Yesterday, I did an experiment to automatically launch a test server. I did not success with my experiment and because of that, search engine is down. Thus, you saw the error of connection refuse to search engine in the web page.
