### ISSUE TITLE
Update/Design web UI requirements

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#61]
web UI requirements were identified in #84. 

this ticket is to analyse the current design in relation to feedback from the community

**Comment by ducvan0212** [comment]
I did not find where the issue is, @hdliv

**Comment by hdliv** [comment]
no issue @ducvan0212 .  ... just that arlin and i are going to look at design again

**Comment by arlin** [comment]
The comments in #75, #76 and #77 are responsive to this.  The first two have the requirements.  We need this also for #77.   @hdlv, when you (or we) have finished filling in the requirements for #77 (extract from file workflow), then we can close this.

**Comment by arlin** [comment]
OK, I just did this, so I'm moving this over to "In review".  @hdliv, can you review what I wrote for #75, #76 and #77, and if satisfied, move this ticket into "done".

**Comment by hdliv** [comment]
@arlin justmade 2 little changes and moving this to done --
