### ISSUE TITLE
change tree format

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#62]
The tree should be in the format that is more common in systematics, which are square.

**Comment by hdliv** [comment]
![img_1386](https://cloud.githubusercontent.com/assets/6361361/14507318/0aa31488-0190-11e6-985f-dad16b0376da.jpg)

**Comment by hdliv** [comment]
[Fig. 13 Tree Werner et al.  (Phycologia Manuscript PH11-10) - July 2011.pdf](https://github.com/phylotastic/phylotastic-portal/files/217856/Fig.13.Tree.Werner.et.al.Phycologia.Manuscript.PH11-10.-.July.2011.pdf)

**Comment by hdliv** [comment]
![img_1371](https://cloud.githubusercontent.com/assets/6361361/14507343/310140d2-0190-11e6-8bd1-4c1cfb14f569.jpg)

**Comment by hdliv** [comment]
@ducvan0212

**Comment by ducvan0212** [comment]
The tree now looks like your description. Thanks for your comment.

**Comment by hdliv** [comment]
@ducvan0212 I will move this ticket over to in review

**Comment by hdliv** [comment]
@ducvan0212    @arlin  and I both looked at the screenshot you sent and I am moving this ticket back to done.  the tree looks great!! thanks
