### ISSUE TITLE
jobs view freeze

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#66]
Occasionally the jobs view becomes unusable in Chrome on OSX (Version 49.0.2623.87 (64-bit)).  

When I click on an item (any item), the URL changes from <host>/trees to <host>/trees#, but nothing happens.  This makes the jobs table unusable, because I can't access anything. 

This behavior does not occur reliably.  I have not been able to figure out what triggers it.  

The expected behavior is that clicking on a job opens up another table with information on the job, including clickable links to results.

**Comment by hdliv** [comment]
@arlin I am not sure if this is related or an independent issue that I posted in ticket #70
