### ISSUE TITLE
redundant notifications

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#67]
when the jobs view is activated, and the portal tries to run all the jobs again, there are redundant notifications.
![screen shot 2016-04-14 at 3 09 02 pm](https://cloud.githubusercontent.com/assets/1659198/14540459/1caeb0f6-0253-11e6-93a0-993059b137ef.png)

**Comment by ducvan0212** [comment]
It is not a bug. I intended that. But I did some changes in notification display.

![screen shot 2016-04-16 at 9 37 01 am](https://cloud.githubusercontent.com/assets/1614884/14581916/db92086a-03b6-11e6-9d61-ce2e17370f5a.png)

There is only notification when the tree is successfully constructed. 
The green navigator indicates there is a new tree which is just created while the red navigator indicates there is a tree which needs users decision.

**Comment by hdliv** [comment]
@ducvan0212 it looks like you have fixed this
should we move it to review?
