### ISSUE TITLE
species service bug

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#71]
Get a list:

"list_extra_info"=>"",
 "list_keywords"=>["bird", "endangered species", "Everglades"],
 "list_curator"=>"HD Laughinghouse",
 "list_origin"=>"webapp",
 "list_curation_date"=>"02-24-2016",
 "list_source"=>"Des",
 "list_description"=>"A list on the bird species add their endangered, threatened or invasive status",
 "list_focal_clade"=>"Aves",
 "list_id"=>12,
 "list_author"=>["Bass", "O. & Cunningham", "R."],
 "list_title"=>"Bird Species List for Everglades National Park",
 "list_date_published"=>"01-01-2006",
 "is_list_public"=>false}

Replace species:
"{\"status_code\": 204, \"message\": \"No list found with ID 12\", \"user_id\": \"ducvan0212@gmail.com\"}"

I can get the list 12 but unable to update it because "No list found with ID 12".

**Comment by abusalehmdtayeen** [comment]
Bug has been fixed.
