### ISSUE TITLE
hide unimplemented features

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#74]
Hide anything that is not fully implemented and ready for testing.  The list of things to hide includes: 

* Menu bar: Explore, About, FAQ, Videos, Feedback
* Home: edit profile 
* new_from_prebuilt: hide "from your own list" 
* new_from_taxon: show "I want to use all . . . ", hide the 2 others 
* trees/<id>/edit: "Choose source..." (we only use OT), "Any extras"

**Comment by ducvan0212** [comment]
In new_from_prebuilt, "from your own list" will be back as soon as Abu publishes his modified species services. I will try to make it works again as soon as possible.
In new_from_taxon, the NCBI genome case is implemented. Is it fine if I will only hide "Found in <country>" part?

**Comment by arlin** [comment]
The portal that I am viewing has 3 options:  

<img width="440" alt="screen shot 2016-04-21 at 6 20 27 pm" src="https://cloud.githubusercontent.com/assets/1659198/14726130/0265872e-07ee-11e6-8716-4903c8291da5.png">

which of these are implemented?   Do you have other ones that are not running on the server?

**Comment by arlin** [comment]
If you are just about to finish "from your own list", then please keep it.

**Comment by ducvan0212** [comment]
@arlin These 2 cases are implemented
![screen shot 2016-04-21 at 4 37 20 pm](https://cloud.githubusercontent.com/assets/1614884/14726429/73e0e04c-07df-11e6-8d66-f81305649f63.png)
![screen shot 2016-04-21 at 4 37 11 pm](https://cloud.githubusercontent.com/assets/1614884/14726430/73f05ec8-07df-11e6-8988-a0c1ec1c3dc7.png)

**Comment by arlin** [comment]
OK, but in trees/*/edit we still need to hide  (1)  choice of source (we only use OT), (2) the checkboxes for branch lengths and images (as images are automatic),

**Comment by ducvan0212** [comment]
I will do that after the database is reset.

**Comment by arlin** [comment]
This is not yet done.  We are still seeing unimplemented options in the trees/*/edit view.

**Comment by ducvan0212** [comment]
#87 @abusalehmdtayeen wants to test more before he resets his service. I have to wait for him

**Comment by arlin** [comment]
I don't see how this depends on #87.  The goal of hiding unimplemented features is that we want to create a version of the portal for testing and improvement.  We want a version of the portal where every feature works at least 90 % of the time.

**Comment by ducvan0212** [comment]
Prof. @arlin, I can remove records in database right now for you but this is NOT a test version because the database for now is not reset. I expected a database reset from last week so you can have a clean database for testing (and a clean database means no more errors from previous development) but Abu wants more time to reset his service. If I do my database reset first then old records in Abu service will be imported new database => dirty again.

**Comment by ducvan0212** [comment]
I will remove records in current database so you can see the portal as you expect.

**Comment by arlin** [comment]
@ducvan0212, I think you are mixing up two issues.  One of them is hiding interface features that are not implemented.  The other is resetting the database when we change the list requirements for an ISO-compliant date. Please explain to me how it is impossible for you to change what the interface looks like without resetting the database.  If you have to reset the database every time you re-launch the portal, that is a design flaw.

**Comment by ducvan0212** [comment]
(1) choice of source (we only use OT) => Phylo source is taken from database and then rendered in interface. Anyway, I removed all the trees associated with Phylomatic and TreeBase. 

(2) the checkboxes for branch lengths and images (as images are automatic) => This will be hidden because it is just in interface.

The problem is tiny. Doing this take just a few seconds. The point is I expected I would do these modifications right after the database reset which was planned from last week.

**Comment by arlin** [comment]
Please explain #1 further.  Are you suggesting that the choices are not hard-coded in the interface, but are taken from a database that is external to the portal?

**Comment by ducvan0212** [comment]
The source of phylo tree is OpenTree, Phylomatic and TreeBase. There are 3 records in table PhyloSource in database respectively to each source. When you open tree creating interface, these records are fetched from database and rendered in selection box. When you click 'create tree', a new tree is created with association to id of one of these three records. 

I removed the recored for Phylomatic and TreeBASE and all the trees associated with these records so you can see only OpenTree in selection box of tree creating view.

**Comment by ducvan0212** [comment]
These sources can be hard-code in interface only. I agree but if I code this way, I have to do extra work that is verification that the user input is in the range of OpenTree, Phylomatic and TreeBase or not.

**Comment by ducvan0212** [comment]
For example, you can send a request to ask the portal generate a tree from OpenTree but if I inspect elements in the browser and change tree source field in tree creating form to "abcdef" then that will cause errors when there is no verification in server side. 

Moreover, if you want to manage the source of tree in a web interface (assume you are an admin and you can access administration pages), I can display phylo source by extracting record from table in database, allow you delete or edit these source and update them to database. If I save phylo source by a string field in Tree table, I dont think implementation management phylo source is a trivial task as it should be.

**Comment by ducvan0212** [comment]
Sorry for my bad English, Professor. I tried my best to describe my design choice. If you are still confused about anything, I will answer as soon as possible and make any changes if it is sound.
