### ISSUE TITLE
plan functional tests for lists workflow

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#75]
Develop plan for functional tests.  Assemble test inputs and expected outputs.

**Comment by arlin** [comment]
this is our initial sketch 

## Basic workflow 
* user chooses "Lists" workflow
   * system displays choice of lists for user
      * there must be at least 10 interesting lists 
* user chooses a list
   * system retrieves tree, displays for user 
   * system offers option to save to disk or clipboard
* user saves tree 

## Functional testing 

Normal conditions
* GUI responds as described above 
   * lists at least 10 lists immediately
* tree is displayed within 30 seconds
* expected OT tree is obtained for each list 

Exceptions 
* no tree retrieved for dino list: provide message

**Comment by arlin** [comment]
@hdliv, we have written out the test requirements.  If you have the 10 cases assembled and uploaded to github, then you can put this ticket into review.

**Comment by hdliv** [comment]
located here: https://github.com/phylotastic/phylotastic/tree/master/testing/Lists_workflow
