### ISSUE TITLE
plan functional tests for taxon workflow

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#76]
Develop plan for functional tests.  Assemble test inputs and expected outputs.

**Comment by arlin** [comment]
### Basic workflow with 2 branches
* user chooses "Taxon" workflow
   * system prompts for taxon name 
      * provides helpful hints (see above)
* user enters name, e.g., "Canidae"
   * system prompts for choice of 
      * all species 
      * species with genomes in NCBI
* user chooses all species or genomes
   * system retrieves list, gets tree, displays for user 

### Functional requirements  
* GUI responds as described above 
* hints are helpful to get binomials from common names
* tree is displayed within 30 seconds
* expected tree is obtained for each list 
   * all species if user chooses "all"
   * NCBI genome species if user chooses that 

### Test cases
* pick 10 taxa for testing (from a few  to 300 species)
   * Passerina (7), Canidae, Felinae, Felidae, 
   * find out how many have NCBI genomes
* get OT tree for 10 taxa, with or without genome restriction

**Comment by hdliv** [comment]
located here: https://github.com/phylotastic/phylotastic/tree/master/testing/Taxon_workflow

**Comment by arlin** [comment]
@hdliv, please be sure to add some test for the "get all species" branch of this workflow.  Canidae, Felidae,  Ascarididae, are some that should work
