### ISSUE TITLE
plan functional tests for extract-from-source workflow

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#77]
Develop plan for functional tests.  Assemble test inputs and expected outputs.

**Comment by arlin** [comment]
### Basic workflows 
Basic from URL
* user chooses "Extract from source" workflow
   * system prompts for source (URL or file upload)
* user enters URL 
   * system extracts names, gets tree, displays to user 
   
Basic from file 
* user chooses "Extract from source" workflow
   * system prompts for source (URL or file upload)
* user uploads file  
   * system extracts names, gets tree, displays to user 

### Functional requirements 

We didn't get to this yet. 

### Test cases

For input files, we can just recycle some of the material from the list and taxon test cases.  For instance, we can take the "pets" or "top 20" list and put the contents into an xls or text file.  However, it is important to create a variety of different files of each type, because the parser may be sensitive to the exact format.

**Comment by hdliv** [comment]
located here: https://github.com/phylotastic/phylotastic/tree/master/testing/Extract_from_file_workflow
