### ISSUE TITLE
can't log in - error from google

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#81]
I was getting a database error due to an expired token, so I logged out and attempted to log back in again.  However, I found that this was impossible.  Clicking on the G+ button to log in gives an error: 

## error text 
400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://128.123.63.10:3000/users/auth/google_oauth2/callback

## Details

access_type=offline
scope=email profile https://www.googleapis.com/auth/offline
response_type=code
redirect_uri=http://128.123.63.10:3000/users/auth/google_oauth2/callback
state=fed7b9bddee157c9eb6e75768081d7be71e50c3b915627ef
prompt=consent
client_id=936627843472-tbvfhfohauanrehv1l94a6lrj5lvq0r3.apps.googleusercontent.com

**Comment by ducvan0212** [comment]
Can you re-try? I removed lpks.test@gmail.com in database.

**Comment by ducvan0212** [comment]
@thanhnh-infinity Would you please check again config of google app?

**Comment by ducvan0212** [comment]
@arlin Cant you still sign in?

**Comment by arlin** [comment]
I'm still getting the same error in Chrome.  I also tried Safari and got the same error.  I have never accessed the portal with Safari before, so this means that it is not a stale token issue.

**Comment by ducvan0212** [comment]
@arlin The nature of error is from Google app so changing browsers will not solve the problem. I changed authentication to my google app. Would you please re-try? 
http://stackoverflow.com/questions/18166090/how-to-deploy-google-glass-java-starter-on-aws-ec2-instance-with-raw-ip-address

**Comment by ducvan0212** [comment]
It will allow you to sign in but you cant do other things because Abu will verify token from Thanh google app. If you can log in using my google app config, then I can send the config to Thanh to update his google app

**Comment by arlin** [comment]
client id is different, but error is still the same

access_type=offline
scope=email profile https://www.googleapis.com/auth/offline
response_type=code
redirect_uri=http://128.123.63.10:3000/users/auth/google_oauth2/callback
state=89702526202d2926a01db16fa8f3ad9de5375337b71a8638
prompt=consent
client_id=304895613392-c5fgo81fpbqqlpl17jpoqmqdinvdl8j8.apps.googleusercontent.com

**Comment by thanhnh-infinity** [comment]
Hi Van, the issue is that Google OAuth 2 does not allow callback is IP address.
I assigned callback for you they are :  http://phylo.cs.nmsu.edu:3000 and http://phylo.cs.nmsu.edu:3000/users/auth/google_oauth2/callback
They are NOT : http://128.123.63.10:3000/users/auth/google_oauth2/callback.

**Comment by thanhnh-infinity** [comment]
http://stackoverflow.com/questions/14238665/can-a-public-ip-address-be-used-as-google-oauth-redirect-uri

**Comment by thanhnh-infinity** [comment]
I guess that, Dr @arlin accesses Web by IP address instead of domain.

**Comment by ducvan0212** [comment]
@arlin Please use portal via http://phylo.cs.nmsu.edu:3000/
@thanhnh-infinity thank you

**Comment by arlin** [comment]
that works for me.  please notify everyone in gitter to use the domain address rather than the ip

**Comment by arlin** [comment]
then you can close this ticket

**Comment by ducvan0212** [comment]
It looks like only Dr. @arlin and Dail actively tried the portal so it is better to invite people in gitter test the portal after I do a database reset which will be done only after I hear some comments from Dr @arlin and @hdliv for current portal version.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Let me know when you reset the database. I have to do that in my end too.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen Of course. Thank you very much, Abu 👍

**Comment by hdliv** [comment]
@ducvan0212 i am getting 


400. That’s an error.

Error: invalid_request

Invalid parameter value for redirect_uri: Raw IP addresses not allowed: http://128.123.63.10:3000/users/auth/google_oauth2/callback

**Comment by arlin** [comment]
@hdliv use  http://phylo.cs.nmsu.edu:3000/ from now on instead of the IP address

**Comment by hdliv** [comment]
@arlin thanks
