### ISSUE TITLE
add column 'class'

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#82]

**Comment by hdliv** [comment]
@ducvan0212 add this column.  see email

**Comment by ducvan0212** [comment]
@abusalehmdtayeen let me know when you finished your modification

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 @hdliv : class property has been added to the species list database. User can now save class of a species in list server.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I have to add "list_class" or what to json request?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : Just add "class" in the species json object like "family" and "order".

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : The list zip files that I sent you earlier do not have the class column. You can either add the class column and put "" value in the csv files for the existing lists or ask Dail to send you all the zip files again with the correction for date format and class property.

**Comment by ducvan0212** [comment]
@hdliv please check whether or not this function works on server? I can not test because I dont have files
