### ISSUE TITLE
database reset

### ISSUE THREAD

**Issue by ducvan0212** [phylotastic/phylotastic-portal#87]

**Comment by ducvan0212** [comment]
I am planning there are 2 separate servers for the portal:
- Test server: this server will be updated frequently with new features (and there will be some bugs in there). I will do database reset in this server whenever I want. 
- Production server: this server will be updated only when new features are tested in test server and are allowed to be published.

I will create a production server (I hope the portal current version is stable enough) and reset database for test server tomorrow so you can not access portal during the time I do deployment. 
@abusalehmdtayeen Can you do database reset in species list service tomorrow morning?

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I would suggest to do the database reset after we do some more tests. For example, when we implement the module to check the validity and format of CSV files, we have to test that feature.

**Comment by ducvan0212** [comment]
That is fine.

Do you close port 80 in phylo.cs.nmsu.edu? I am trying to deploy a server to port 80

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : No, I did not close port 80. Thanh and I tried to use that port to host the service registry. But it did not work for some reason. So we hosted it in 8080 port. Please try some other port.

**Comment by epontell** [comment]
Are you connecting from inside or outside? It is possible that NMSU has started filtering certain ports

**Comment by ducvan0212** [comment]
> On
a Web server or Hypertext Transfer Protocol daemon, port 80 is the port that the server "listens to" or expects to receive from a Web client, assuming that the default was taken when the server was configured or set up

I tried to set up the portal to serve requests in port 80 so if NMSU has started filtering port 80, I guess we will have to use http://phylo.cs.nmsu.edu:xxxx (xxxx is port number) instead of http://phylo.cs.nmsu.edu. I just try to make the url of the portal look a little bit more elegant :)

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : I have re-setted the species list database. Now there is no lists in the database. I have made two changes according to the new requirements. 
1. Changed the date format to ISO standard and date type to string which will allow users to put empty values or "NA" values. 
2. Added the class attribute in species data. So to insert list you have to add the class property to every species json object.

**Comment by arlin** [comment]
you mean by "have to add" in (2) that "class" is required?  is that what we want?

**Comment by abusalehmdtayeen** [comment]
@arlin : by "have to" I mean the property must exist in the json format when inserting a list, but it is up to the user to put values in it or leave it empty("") or put "NA" value. The value is not mandatory in this case.

**Comment by ducvan0212** [comment]
Portal database is reset. I tested file, link and taxon use case and they worked. The list test case I leave @hdliv test. Date format and Class attribute are also updated. If there is error, please let me know.
