### ISSUE TITLE
Quality of tree image when downloaded

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#89]
I downloaded the .png file of a tree I generated through the portal.  When I put it on a ppt presentation the image was quite pixelated.  Can we increase the quality?

**Comment by ducvan0212** [comment]
I afraid it is impossible to increase quality. Even when increasing quality, if you zoom in to a specific degree, the image will be still pixelated.

**Comment by hdliv** [comment]
ok.  I will close this then

**Comment by bomeara** [comment]
Couldn't we export as a vector format (i.e., pdf, svg) rather than raster? Then it'd be easy to scale.

**Comment by hdliv** [comment]
@bomeara thanks for chiming in.   @ducvan0212 this is not a priority right now..  so we can leave it here in the backlog while other parts of the portal are updated.

**Comment by ducvan0212** [comment]
@bomeara thanks, I think png with transparent background is requirement. But anyway, I allowed users to download svg image so they can import to other tools and convert to png whenever they want.

This feature is updated in server. You are more than welcome to test.
