### ISSUE TITLE
workflow1 connection error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#91]
1. choose pre-built
2. choose Illinois invasive plants (or other)
3.  select OpenTree as source, get tree

The result is an error.  

Errno::ECONNREFUSED in TreesController#create
Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">Tree 213</field><field name=\"type\">Tree</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">Tree</field><field name=\"public_b\">false</field><field name=\"chosen_species_text\">{\"Achyranthes japonica\":\"1\",\"Acer ginnala\":\"1\",\"Allium vineale\":\"1\",\"Acer platanoides\":\"1\",\"Ailanthus altissima\":\"1\",\"Alliaria petiolata\":\"1\"}</field><field name=\"description_text\">sdfsdf</field></doc></add>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP http://localhost:8982/solr/development/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}

Extracted source (around line #37):
35
36
37
38
39
40
              
    params["tree"]["chosen_species"] = params["tree"]["chosen_species"].to_json  
    @tree = current_user.trees.build(tree_params)
    if @tree.save
      flash[:success] = "Tree is being constructed! We will inform you when your tree is ready"
      job_id = TreesWorker.perform_async(@tree.id)
      @tree.update_attributes( bg_job: job_id,

**Comment by ducvan0212** [comment]
#93
