### ISSUE TITLE
workflow2 error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#92]
1. select tree from taxon workflow
2.  enter "canidae"
3.  choose all species, get tree

result is an error 

Errno::ECONNREFUSED in ConTaxonsController#create
Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">Tree 214</field><field name=\"type\">Tree</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">Tree</field><field name=\"public_b\">false</field><field name=\"chosen_species_text\">{\"Aelurodon taxoides\":\"1\",\"Aelurodon asthenostylus\":\"1\",\"Aelurodon ferox\":\"1\",\"Aelurodon montanensis\":\"1\",\"Aelurodon mcgrewi\":\"1\",\"Aelurodon stirtoni\":\"1\",\"Cynotherium sardous\":\"1\",\"Rhizocyon oregonensis\":\"1\",\"Paratomarctus temerarius\":\"1\",\"Paratomarctus euthos\":\"1\",\"Archaeocyon pavidus\":\"1\",\"Archaeocyon leptodus\":\"1\",\"Archaeocyon falkenbachi\":\"1\",\"Metatomarctus canavus\":\"1\",\"Psalidocyon marianae\":\"1\",\"Protomarctus optatus\":\"1\",\"Neocynodesmus delicatus\":\"1\",\"Protepicyon raki\":\"1\",\"Desmocyon matthewi\":\"1\",\"Desmocyon thomsoni\":\"1\",\"Paracynarctus kelloggi\":\"1\",\"Paracynarctus sinclairi\":\"1\",\"Microtomarctus conferta\":\"1\",\"Otarocyon cooki\":\"1\",\"Otarocyon macdonaldi\":\"1\",\"Paraenhydrocyon robustus\":\"1\",\"Paraenhydrocyon josephi\":\"1\",\"Sunkahetanka geringensis\":\"1\",\"Procynodictis vulpiceps\":\"1\",\"Procynodictis progressus\":\"1\",\"Hesperocyon gregorious\":\"1\",\"Hesperocyon coloradensis\":\"1\",\"Hesperocyon gregarius\":\"1\",\"Euoplocyon spissidens\":\"1\",\"Euoplocyon brachygnathus\":\"1\",\"Philotrox condoni\":\"1\",\"Leptocyon vulpinus\":\"1\",\"Leptocyon gregorii\":\"1\",\"Leptocyon vafer\":\"1\",\"Carpocyon limosus\":\"1\",\"Carpocyon robustus\":\"1\",\"Carpocyon webbi\":\"1\",\"Carpocyon compressus\":\"1\",\"Ectopocynus intermedius\":\"1\",\"Ectopocynus simplicidens\":\"1\",\"Ectopocynus antiquus\":\"1\",\"Osbornodon iamonensis\":\"1\",\"Osbornodon brachypus\":\"1\",\"Osbornodon scitulus\":\"1\",\"Osbornodon renjiei\":\"1\",\"Osbornodon wangi\":\"1\",\"Osbornodon sesnoni\":\"1\",\"Osbornodon fricki\":\"1\",\"Epicyon haydeni\":\"1\",\"Epicyon aelurodontoides\":\"1\",\"Epicyon saevus\":\"1\",\"Eucyon davisi\":\"1\",\"Cormocyon copei\":\"1\",\"Cormocyon haydeni\":\"1\",\"Cerdocyon thous\":\"1\",\"Borophagus pugnator\":\"1\",\"Borophagus hilli\":\"1\",\"Borophagus littoralis\":\"1\",\"Borophagus diversidens\":\"1\",\"Borophagus secundus\":\"1\",\"Borophagus orc\":\"1\",\"Borophagus dudleyi\":\"1\",\"Borophagus parvus\":\"1\",\"Cynarctoides harlowi\":\"1\",\"Cynarctoides roii\":\"1\",\"Cynarctoides acridens\":\"1\",\"Cynarctoides gawnae\":\"1\",\"Cynarctoides lemur\":\"1\",\"Cynarctoides luskensis\":\"1\",\"Cynarctoides emryi\":\"1\",\"Prohesperocyon wilsoni\":\"1\",\"Tomartus euthos\":\"1\",\"Tomarctus brevirostris\":\"1\",\"Tomarctus hippophaga\":\"1\",\"Phlaocyon achoros\":\"1\",\"Phlaocyon minor\":\"1\",\"Phlaocyon leucosteus\":\"1\",\"Phlaocyon latidens\":\"1\",\"Phlaocyon marslandensis\":\"1\",\"Phlaocyon yatkolai\":\"1\",\"Phlaocyon multicuspus\":\"1\",\"Phlaocyon mariae\":\"1\",\"Phlaocyon annectens\":\"1\",\"Phlaocyon taylori\":\"1\",\"Mesocyon temnodon\":\"1\",\"Mesocyon coryphaeus\":\"1\",\"Mesocyon brachyops\":\"1\",\"Cynodesmus thooides\":\"1\",\"Cynodesmus martini\":\"1\",\"Oxetocyon cuspidatus\":\"1\",\"Enhydrocyon pahinsintewakpa\":\"1\",\"Enhydrocyon basilatus\":\"1\",\"Enhydrocyon crassidens\":\"1\",\"Enhydrocyon stenocephalus\":\"1\",\"Caedocyon tedfordi\":\"1\",\"Cynarctus voorhiesi\":\"1\",\"Cynarctus marylandica\":\"1\",\"Cynarctus crucidens\":\"1\",\"Cynarctus galushai\":\"1\",\"Cynarctus saxatilis\":\"1\",\"Lycalopex sp. Fuegian dog\":\"1\",\"Lycalopex fulvipes\":\"1\",\"Lycalopex gymnocercus\":\"1\",\"Lycalopex griseus\":\"1\",\"Lycalopex culpaeus\":\"1\",\"Lycalopex vetulus\":\"1\",\"Lycalopex sechurae\":\"1\",\"Cuon texanus\":\"1\",\"Cuon alpinus\":\"1\",\"Vulpes environmental sample\":\"1\",\"Vulpes stenognathus\":\"1\",\"Vulpes bengalensis\":\"1\",\"Vulpes pallida\":\"1\",\"Vulpes cana\":\"1\",\"Vulpes chama\":\"1\",\"Vulpes vulpes\":\"1\",\"Vulpes lagopus\":\"1\",\"Vulpes corsac\":\"1\",\"Vulpes rueppellii\":\"1\",\"Vulpes zerda\":\"1\",\"Vulpes velox\":\"1\",\"Vulpes macrotis\":\"1\",\"Vulpes sp.\":\"1\",\"Vulpes ferrilata\":\"1\",\"Otocyon megalotis\":\"1\",\"Lycaon pictus\":\"1\",\"Speothos venaticus\":\"1\",\"Atelocynus microtis\":\"1\",\"Chrysocyon brachyurus\":\"1\",\"Nyctereutes abdeslami\":\"1\",\"Nyctereutes procyonoides\":\"1\",\"Canis anthus\":\"1\",\"Canis sp. Russia/33,500\":\"1\",\"Canis sp. Belgium/36,000\":\"1\",\"Canis environmental sample\":\"1\",\"Canis spelaeus\":\"1\",\"Canis hyaena\":\"1\",\"Canis primigenius\":\"1\",\"Canis cedazoensis\":\"1\",\"Canis apolloniensis\":\"1\",\"Canis edwardii\":\"1\",\"Canis alopex\":\"1\",\"Canis dirus\":\"1\",\"Canis ferox\":\"1\",\"Canis armbrusteri\":\"1\",\"Canis lepophagus\":\"1\",\"Canis lycaon\":\"1\",\"Canis simensis\":\"1\",\"Canis mesomelas\":\"1\",\"Canis aureus\":\"1\",\"Canis adustus\":\"1\",\"Canis sp. CANInt1\":\"1\",\"Canis lupus\":\"1\",\"Canis latrans\":\"1\",\"Canis sp.\":\"1\",\"Canis rufus\":\"1\",\"Urocyon progressus\":\"1\",\"Urocyon cinereoargenteus\":\"1\",\"Urocyon littoralis\":\"1\",\"Dusicyon avus\":\"1\",\"Dusicyon australis\":\"1\"}</field><field name=\"description_text\">dogs</field></doc></add>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP http://localhost:8982/solr/development/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}

Extracted source (around line #33):
31
32
33
34
35
36
              
        extraction = @con_taxon.create_raw_extraction(species: resolved)
        
        tree = current_user.trees.create( bg_job: "-1", 
                                          status: "resolved", 
                                          raw_extraction_id: extraction.id,
                                          chosen_species: chosen_species,

**Comment by ducvan0212** [comment]
#93
