### ISSUE TITLE
workflow3a connection error

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#93]
1. choose extract from source
2. enter URL for wikipedia ant page
3.  choose to get tree

result is an error: 

Errno::ECONNREFUSED in ConLinksController#create
Connection refused - {:data=>"<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">Tree 215</field><field name=\"type\">Tree</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">Tree</field><field name=\"public_b\">false</field></doc></add>", :headers=>{"Content-Type"=>"text/xml"}, :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update", :uri=>#<URI::HTTP http://localhost:8982/solr/development/update?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}

Extracted source (around line #9):
7
8
9
10
11
12
              
      flash[:success] = "Processing URL!"
      job_id = ExtractionsWorker.perform_async(@con_link.id, "ConLink", current_user.id)
      current_user.trees.create(bg_job: job_id, status: "extracting")
      redirect_to trees_path
    else
      @con_file = ConFile.new

**Comment by ducvan0212** [comment]
I tried to use Ansible and Capistrano to auto-deploy the server. It has nothing wrong with the code of the portal.

**Comment by ducvan0212** [comment]
The server is back, prof @arlin. This error just relates to my experiment with auto deployment.
