### ISSUE TITLE
can't remove taxon subset job

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic-portal#94]
I removed old jobs from several workflows.  However, I could not remove jobs from the taxon subset workflow.  This is the error that I got: 

Unknown action
The action 'destroy' could not be found for SubsetTaxonsController

**Comment by ducvan0212** [comment]
It is not a bug. I forgot to implement this feature. I pushed this feature to the server.

**Comment by arlin** [comment]
@ducvan0212 , don't close until someone tests.  moving this back to "In review".

**Comment by arlin** [comment]
OK, tested this and I now can remove taxon subsets.  Thanks!

**Comment by ducvan0212** [comment]
Oh, I moved this ticket to "Done" column and it is automatically changed to "Closed" issue and removed "In review" label. I intently kept "In review" label in waffle but in git, it is removed. It is weird. Sorry about that, prof.
