### ISSUE TITLE
no 'failed because'  message

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#96]
While uploading arctic terrestrial mammals, there was an error with the zip file 'failed because' .  'failed because' was blank.  Need to know why it failed.

**Comment by hdliv** [comment]
![screen shot 2016-05-17 at 15 26 52](https://cloud.githubusercontent.com/assets/6361361/15336364/3df4144e-1c44-11e6-8e59-9cff066f9985.png)

**Comment by hdliv** [comment]
@arlin and i traced this down to the bad character:   æ

**Comment by arlin** [comment]
We determined (I think) that this is *not* a valid unicode char.  We opened the file in TextWrangler and asked it to save with unicode equivalents, then tried again, and the revised file was uploaded without an error.  

@hdliv, could you please save the bad file as a test file?

**Comment by hdliv** [comment]
[Archive 3.zip](https://github.com/phylotastic/phylotastic-portal/files/269104/Archive.3.zip)

**Comment by ducvan0212** [comment]
I added the reason why the server failed to proceed the file. For Dail's file, the error is "invalid byte sequence in UTF-8" but it does not provide where (I mean at which line) the sequence causing error is.
