### ISSUE TITLE
private list to public list

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#97]
It would be nice to allow a private list to be public after the list has already been uploaded as private

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I checked in species document but I dont see api to update a list anymore. 
@hdliv I will implement this feature. Once a list is published, it will remain publicly accessed from that on.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 : The API to update the contents (species data) of a list still exists in the documentation. Are you talking about updating the list properties (metadata) or update the list as a whole? If you need either of them, then I have to create that API for you.

**Comment by ducvan0212** [comment]
Yeah, hdliv wants to update public property of a list

**Comment by hdliv** [comment]
@ducvan0212 @abusalehmdtayeen this is not urgent.  just wanted to be able to make a private list public, after it has already been uploaded into the portal

**Comment by ducvan0212** [comment]
Suppose we have 2 databases: d1, d2. If list L in d1 is updated public attributes then for now, the only way to know L is updated is polling @abusalehmdtayeen services from d2. However it is costly and unscalable. What do you think, Abu?

**Comment by ducvan0212** [comment]
After changing from private to public, list is not included in public list api. @abusalehmdtayeen you can see list 4 is public but when queuing public lists, it is not in returned response.

**Comment by ducvan0212** [comment]
@abusalehmdtayeen

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 , This issue is fixed now. You have to send boolean type value when you are modifying the type of list. I had to remove the list 4 which caused problem for this.

**Comment by hdliv** [comment]
@abusalehmdtayeen @ducvan0212 can i close this?

**Comment by abusalehmdtayeen** [comment]
@hdliv , @ducvan0212 should check first if he faces any other problem with this. Then you can close this.

**Comment by ducvan0212** [comment]
I think it can be closed now.

**Comment by hdliv** [comment]
@ducvan0212 yes I am closing this.  we have already discussed this
