### ISSUE TITLE
tree completed but nowhere to be found

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#98]
I am trying to reate the tree for the prebuilt example: Top 20 popular species.  I click to create the tree and am redirected to the Jobs view.  After a while I get the notice that the tree was created...but there is no tree.

**Comment by hdliv** [comment]
<img width="413" alt="screen shot 2016-05-19 at 12 32 30" src="https://cloud.githubusercontent.com/assets/6361361/15411422/e5da6e10-1ded-11e6-98fe-6967c6f3b36d.png">

**Comment by hdliv** [comment]
<img width="498" alt="screen shot 2016-05-19 at 12 32 58" src="https://cloud.githubusercontent.com/assets/6361361/15411426/ea318dd6-1ded-11e6-8f07-e06880b85971.png">

**Comment by ducvan0212** [comment]
The trees were hidden. I forgot to uncomment this partial of code. Sorry about that :)

**Comment by hdliv** [comment]
@ducvan0212 i an see the trees now
