### ISSUE TITLE
error message Choose from Specified Taxon

### ISSUE THREAD

**Issue by hdliv** [phylotastic/phylotastic-portal#99]
I want all the species of Ascomycota that have genomes.  When i query this I get an error

**Comment by hdliv** [comment]
![screen shot 2016-05-19 at 18 18 36](https://cloud.githubusercontent.com/assets/6361361/15411507/7b0a5b62-1dee-11e6-84b4-faacd7b11a6d.png)

**Comment by hdliv** [comment]
however, when I search for genomes of Ascomycota...there are 538

**Comment by hdliv** [comment]
![screen shot 2016-05-19 at 18 19 13](https://cloud.githubusercontent.com/assets/6361361/15411522/94316810-1dee-11e6-8f48-ae9cdf92e786.png)

**Comment by ducvan0212** [comment]
![screen shot 2016-05-19 at 10 38 15 pm](https://cloud.githubusercontent.com/assets/1614884/15417389/88addfd6-1e12-11e6-91c4-d18dabc40c27.png)

This is what I got from @abusalehmdtayeen service.

**Comment by abusalehmdtayeen** [comment]
@ducvan0212 @hdliv : give me some time to debug this case. I will get back to you.

**Comment by hdliv** [comment]
@abusalehmdtayeen thanks.  this is not the only instance where it happens, but maybe it is the same bug in all.  Let me know when you finish then I can start trying again :)

**Comment by abusalehmdtayeen** [comment]
@hdliv : I have fixed this issue. Can you please try with more test cases through the web portal? And let me know if you find any other error case for this service.

**Comment by hdliv** [comment]
hi @abusalehmdtayeen now i get this error
![screen shot 2016-05-25 at 09 56 32](https://cloud.githubusercontent.com/assets/6361361/15542545/3c3f6fba-225f-11e6-9c41-cf9f86e28722.png)

**Comment by hdliv** [comment]
@ducvan0212

**Comment by ducvan0212** [comment]
![screen shot 2016-05-25 at 10 29 35 am](https://cloud.githubusercontent.com/assets/1614884/15548001/aec2936a-2263-11e6-8cfd-87ea2048e5ce.png)

This is in my end. Abu's service returned only letter "f" for species list which definitely is not in JSON format. 

I still did not wrapped this JSON parsing line of code so we will know what was going on. If @hdliv wants, I will add error handing for this line of code but it will be harder to observer this kind of error as a tradeoff.

**Comment by abusalehmdtayeen** [comment]
@hdliv : For which input do you get this error?
@ducvan0212 : Which service does not return JSON format?

**Comment by ducvan0212** [comment]
@abusalehmdtayeen I guess @hdliv inputted "Ascomycota" as a taxon and he did test in NCBI taxon scenario. The service which did not return JSON format is resolving names.

**Comment by hdliv** [comment]
Yea it was ascomycota

**Comment by abusalehmdtayeen** [comment]
@hdliv : Since different strains of the subspecies are returned for input "Ascomycota", the number of species gets to more than 1000 which is a pretty big list to resolve. Processing such lists will take time. Do we really need to include these subspecies? Please let me know. I can filter out them as I mentioned to you before. That will make the list half. 

@ducvan0212 : The resolver failed because it exceeded the limit of OpenTree query size for that input. I fixed it.

**Comment by hdliv** [comment]
@abusalehmdtayeen Understood.  we'll have to decide but strains are the final 'tips'.  example, the pathogenicity of E. coli, for example, is at the strain level where different strains can differ with 1 million bp.

**Comment by hdliv** [comment]
@abusalehmdtayeen there is a new ticket about the pruning phylo_webservices #27

**Comment by hdliv** [comment]
@abusalehmdtayeen can we close this ticket?

**Comment by abusalehmdtayeen** [comment]
@hdliv : +1:  you can close this ticket.

**Comment by hdliv** [comment]
this has been fixed
